import { enUS } from "@clerk/localizations";

export const lvLV: typeof enUS = {
  ...enUS,
  locale: "lv-LV",

  backButton: "Atpakaļ",
  badge__default: "Noklusējums",
  badge__primary: "Primārais",
  badge__unverified: "Nepārbaudīts",
  badge__thisDevice: "Šī ierīce",
  badge__userDevice: "Lietotāja ierīce",
  badge__you: "Tu",

  signIn: {
    ...enUS.signIn,
    start: {
      ...enUS.signIn.start,
      title: "Pieslēgties {{applicationName}}",
      titleCombined: "Turpināt uz {{applicationName}}",
      subtitle: "Laipni lūgti atpakaļ! Lūdzu, pieslēdzies, lai turpinātu.",
      actionText: "Nav konta?",
      actionLink: "Reģistrēties",
    },
    password: {
      ...enUS.signIn.password,
      title: "Ievadi savu paroli",
      subtitle: "Ievadi paroli, kas saistīta ar tavu kontu",
      actionLink: "Izmantot citu metodi",
    },
    emailCode: {
      ...enUS.signIn.emailCode,
      title: "Pārbaudi savu e-pastu",
      subtitle: "lai turpinātu uz {{applicationName}}",
      formTitle: "Verifikācijas kods",
      resendButton: "Nesaņēmi kodu? Sūtīt vēlreiz",
    },
    emailLink: {
      ...enUS.signIn.emailLink,
      title: "Pārbaudi savu e-pastu",
      subtitle: "lai turpinātu uz {{applicationName}}",
      formTitle: "Verifikācijas saite",
      formSubtitle: "Izmanto verifikācijas saiti, kas nosūtīta uz tavu e-pastu",
      resendButton: "Nesaņēmi saiti? Sūtīt vēlreiz",
      expired: {
        title: "Šī verifikācijas saite ir beigusies",
        subtitle: "Atgriezies sākotnējā cilnē, lai turpinātu.",
      },
      failed: {
        title: "Šī verifikācijas saite nav derīga",
        subtitle: "Atgriezies sākotnējā cilnē, lai turpinātu.",
      },
      loading: {
        title: "Piesakās...",
        subtitle: "Drīz tiksiet novirzīts",
      },
      verified: {
        title: "Veiksmīgi pieteicies",
        subtitle: "Drīz tiksiet novirzīts",
      },
      unusedTab: {
        title: "Šo cilni var aizvērt",
      },
      clientMismatch: {
        title: "Verifikācijas saite nav derīga šai ierīcei",
        subtitle: "Lai turpinātu, atver verifikācijas saiti ierīcē un pārlūkā, no kura uzsāki pieteikšanos",
      },
      verifiedSwitchTab: {
        subtitle: "Atgriezies sākotnējā cilnē, lai turpinātu",
        subtitleNewTab: "Atgriezies jaunajā cilnē, lai turpinātu",
        titleNewTab: "Pieteicies citā cilnē",
      },
    },
    forgotPassword: {
      ...enUS.signIn.forgotPassword,
      title: "Atiestatīt paroli",
      subtitle: "lai atiestatītu tavu paroli",
      subtitle_email: "Vispirms ievadi kodu, kas nosūtīts uz tavu e-pasta adresi",
      subtitle_phone: "Vispirms ievadi kodu, kas nosūtīts uz tavu tālruni",
      formTitle: "Paroles atiestatīšanas kods",
      resendButton: "Nesaņēmi kodu? Sūtīt vēlreiz",
    },
    forgotPasswordAlternativeMethods: {
      ...enUS.signIn.forgotPasswordAlternativeMethods,
      title: "Aizmirsi paroli?",
      blockButton__resetPassword: "Atiestatīt paroli",
      label__alternativeMethods: "Vai pieteikties ar citu metodi",
    },
    alternativeMethods: {
      ...enUS.signIn.alternativeMethods,
      title: "Izmantot citu metodi",
      subtitle: "Rodas problēmas? Vari izmantot jebkuru no šīm metodēm, lai pieteiktos.",
      actionText: "Nav nevienas no šīm?",
      actionLink: "Saņemt palīdzību",
      blockButton__emailCode: "Sūtīt kodu uz {{identifier}}",
      blockButton__emailLink: "Sūtīt saiti uz {{identifier}}",
      blockButton__password: "Pieteikties ar paroli",
      blockButton__phoneCode: "Sūtīt SMS kodu uz {{identifier}}",
      blockButton__backupCode: "Izmantot rezerves kodu",
      blockButton__passkey: "Pieteikties ar passkey",
      blockButton__totp: "Izmantot autentifikatora lietotni",
      getHelp: {
        title: "Saņemt palīdzību",
        content: "Ja rodas problēmas ar pieteikšanos, raksti mums un mēs palīdzēsim atjaunot piekļuvi.",
        blockButton__emailSupport: "Rakstīt atbalstam",
      },
    },
    resetPassword: {
      ...enUS.signIn.resetPassword,
      title: "Iestatīt jaunu paroli",
      formButtonPrimary: "Atiestatīt paroli",
      successMessage: "Tava parole tika veiksmīgi nomainīta. Piesakies, lūdzu uzgaidi brīdi.",
      requiredMessage: "Drošības apsvērumu dēļ ir nepieciešams atiestatīt paroli.",
    },
    noAvailableMethods: {
      ...enUS.signIn.noAvailableMethods,
      title: "Nevar pieteikties",
      subtitle: "Radās kļūda",
      message: "Nevar turpināt pieteikšanos. Nav pieejamu autentifikācijas metožu.",
    },
    accountSwitcher: {
      ...enUS.signIn.accountSwitcher,
      title: "Izvēlēties kontu",
      subtitle: "Izvēlies kontu, ar kuru vēlies turpināt.",
      action__addAccount: "Pievienot kontu",
      action__signOutAll: "Iziet no visiem kontiem",
    },
    passkey: {
      ...enUS.signIn.passkey,
      title: "Izmantot savu passkey",
      subtitle: "Izmantojot savu passkey, tas apstiprina, ka esi tu. Ierīce var prasīt pirkstu nospiedumu, seju vai ekrāna bloķēšanu.",
    },
    totpMfa: {
      ...enUS.signIn.totpMfa,
      title: "Divpakāpju verifikācija",
      subtitle: "Lai turpinātu, ievadi verifikācijas kodu no autentifikatora lietotnes",
      formTitle: "Verifikācijas kods",
    },
    phoneCode: {
      ...enUS.signIn.phoneCode,
      title: "Pārbaudi savu tālruni",
      subtitle: "lai turpinātu uz {{applicationName}}",
      formTitle: "Verifikācijas kods",
      resendButton: "Nesaņēmi kodu? Sūtīt vēlreiz",
    },
    phoneCodeMfa: {
      ...enUS.signIn.phoneCodeMfa,
      title: "Pārbaudi savu tālruni",
      subtitle: "Lai turpinātu, ievadi verifikācijas kodu, kas nosūtīts uz tavu tālruni",
      formTitle: "Verifikācijas kods",
      resendButton: "Nesaņēmi kodu? Sūtīt vēlreiz",
    },
    emailCodeMfa: {
      ...enUS.signIn.emailCodeMfa,
      title: "Pārbaudi savu e-pastu",
      formTitle: "Pārbaudi savu e-pastu",
      resendButton: "Nesaņēmi kodu? Sūtīt vēlreiz",
      subtitle: "lai turpinātu uz {{applicationName}}",
    },
    backupCodeMfa: {
      ...enUS.signIn.backupCodeMfa,
      title: "Ievadi rezerves kodu",
      subtitle: "Rezerves kods ir tas, ko saņēmi, iestatot divpakāpju autentifikāciju.",
    },
  },

  signUp: {
    ...enUS.signUp,
    start: {
      ...enUS.signUp.start,
      title: "Izveidot kontu",
      titleCombined: "Izveidot kontu",
      subtitle: "Laipni lūgti! Lūdzu, aizpildi informāciju, lai sāktu.",
      subtitleCombined: "Laipni lūgti! Lūdzu, aizpildi informāciju, lai sāktu.",
      actionText: "Jau ir konts?",
      actionLink: "Pieteikties",
    },
    continue: {
      ...enUS.signUp.continue,
      title: "Aizpildīt trūkstošos laukus",
      subtitle: "Lūdzu, aizpildi atlikušo informāciju, lai turpinātu.",
      actionText: "Jau ir konts?",
      actionLink: "Pieteikties",
    },
    emailCode: {
      ...enUS.signUp.emailCode,
      title: "Verificēt e-pastu",
      subtitle: "Ievadi verifikācijas kodu, kas nosūtīts uz tavu e-pastu",
      formTitle: "Verifikācijas kods",
      formSubtitle: "Ievadi verifikācijas kodu, kas nosūtīts uz tavu e-pasta adresi",
      resendButton: "Nesaņēmi kodu? Sūtīt vēlreiz",
    },
    emailLink: {
      ...enUS.signUp.emailLink,
      title: "Verificēt e-pastu",
      subtitle: "lai turpinātu uz {{applicationName}}",
      formTitle: "Verifikācijas saite",
      formSubtitle: "Izmanto verifikācijas saiti, kas nosūtīta uz tavu e-pasta adresi",
      resendButton: "Nesaņēmi saiti? Sūtīt vēlreiz",
      loading: { title: "Reģistrējas..." },
      verified: { title: "Veiksmīgi reģistrējies" },
      verifiedSwitchTab: {
        title: "Veiksmīgi verificēts e-pasts",
        subtitle: "Atgriezies jaunajā cilnē, lai turpinātu",
        subtitleNewTab: "Atgriezies iepriekšējā cilnē, lai turpinātu",
      },
      clientMismatch: {
        title: "Verifikācijas saite nav derīga šai ierīcei",
        subtitle: "Lai turpinātu, atver verifikācijas saiti ierīcē un pārlūkā, no kura uzsāki reģistrāciju",
      },
    },
    phoneCode: {
      ...enUS.signUp.phoneCode,
      title: "Verificēt tālruni",
      subtitle: "Ievadi verifikācijas kodu, kas nosūtīts uz tavu tālruni",
      formTitle: "Verifikācijas kods",
      formSubtitle: "Ievadi verifikācijas kodu, kas nosūtīts uz tavu tālruņa numuru",
      resendButton: "Nesaņēmi kodu? Sūtīt vēlreiz",
    },
    restrictedAccess: {
      ...enUS.signUp.restrictedAccess,
      title: "Piekļuve ierobežota",
      subtitle: "Reģistrēšanās pašlaik ir atspējota. Ja uzskat, ka tev vajadzētu piekļuvei, lūdzu sazinieties ar atbalstu.",
      actionText: "Jau ir konts?",
      actionLink: "Pieteikties",
      blockButton__emailSupport: "Rakstīt atbalstam",
    },
  },

  userButton: {
    ...enUS.userButton,
    action__addAccount: "Pievienot kontu",
    action__closeUserMenu: "Aizvērt lietotāja izvēlni",
    action__manageAccount: "Pārvaldīt kontu",
    action__openUserMenu: "Atvērt lietotāja izvēlni",
    action__signOut: "Iziet",
    action__signOutAll: "Iziet no visiem kontiem",
  },

  userProfile: {
    ...enUS.userProfile,
    navbar: {
      ...enUS.userProfile.navbar,
      account: "Konts",
      security: "Drošība",
    },
    start: {
      ...enUS.userProfile.start,
      headerTitle__account: "Konts",
      headerTitle__security: "Drošība",
      profileSection: {
        ...enUS.userProfile.start.profileSection,
        primaryButton: "Rediģēt profilu",
        title: "Profils",
      },
      usernameSection: {
        ...enUS.userProfile.start.usernameSection,
        primaryButton__setUsername: "Iestatīt lietotājvārdu",
        primaryButton__updateUsername: "Mainīt lietotājvārdu",
        title: "Lietotājvārds",
      },
      emailAddressesSection: {
        ...enUS.userProfile.start.emailAddressesSection,
        primaryButton: "Pievienot e-pasta adresi",
        title: "E-pasta adreses",
        detailsAction__primary: "Pabeigt verifikāciju",
        detailsAction__nonPrimary: "Iestatīt kā primāro",
        detailsAction__unverified: "Verificēt",
        destructiveAction: "Noņemt e-pasta adresi",
      },
      connectedAccountsSection: {
        ...enUS.userProfile.start.connectedAccountsSection,
        primaryButton: "Pievienot kontu",
        title: "Saistītie konti",
        actionLabel__connectionFailed: "Savienot vēlreiz",
        actionLabel__reauthorize: "Autorizēt tagad",
        destructiveActionTitle: "Noņemt",
        subtitle__disconnected: "Šis konts ir atvienots.",
      },
      passwordSection: {
        ...enUS.userProfile.start.passwordSection,
        primaryButton__setPassword: "Iestatīt paroli",
        primaryButton__updatePassword: "Mainīt paroli",
        title: "Parole",
      },
      mfaSection: {
        ...enUS.userProfile.start.mfaSection,
        primaryButton: "Pievienot divpakāpju verifikāciju",
        title: "Divpakāpju verifikācija",
        phoneCode: {
          actionLabel__setDefault: "Iestatīt kā noklusējumu",
          destructiveActionLabel: "Noņemt",
        },
        totp: {
          destructiveActionTitle: "Noņemt",
          headerTitle: "Autentifikatora lietotne",
        },
        backupCodes: {
          actionLabel__regenerate: "Ģenerēt vēlreiz",
          headerTitle: "Rezerves kodi",
          subtitle__regenerate: "Iegūt jaunu drošu rezerves kodu kopu. Iepriekšējie rezerves kodi tiks dzēsti.",
          title__regenerate: "Ģenerēt rezerves kodus vēlreiz",
        },
      },
      activeDevicesSection: {
        ...enUS.userProfile.start.activeDevicesSection,
        title: "Aktīvās ierīces",
        destructiveAction: "Iziet no ierīces",
      },
      dangerSection: {
        ...enUS.userProfile.start.dangerSection,
        deleteAccountButton: "Dzēst kontu",
        title: "Dzēst kontu",
      },
    },
    formButtonPrimary__save: "Saglabāt",
    formButtonReset: "Atcelt",
    usernamePage: {
      ...enUS.userProfile.usernamePage,
      title__set: "Iestatīt lietotājvārdu",
      title__update: "Mainīt lietotājvārdu",
      successMessage: "Tavs lietotājvārds ir atjaunināts.",
    },
    emailAddressPage: {
      ...enUS.userProfile.emailAddressPage,
      title: "Pievienot e-pasta adresi",
      verifyTitle: "Verificēt e-pasta adresi",
      formHint: "Tev būs jāverificē šī e-pasta adrese, pirms to var pievienot tavam kontam.",
      emailCode: {
        ...enUS.userProfile.emailAddressPage.emailCode,
        formHint: "E-pastam tiks nosūtīts kods verifikācijai.",
        formTitle: "Verifikācijas kods",
        formSubtitle: "Ievadi verifikācijas kodu, kas nosūtīts uz {{identifier}}",
        resendButton: "Nosūtīt kodu vēlreiz",
        successMessage: "E-pasts {{identifier}} ir pievienots tavam kontam.",
      },
      emailLink: {
        ...enUS.userProfile.emailAddressPage.emailLink,
        formHint: "E-pastam tiks nosūtīta saite verifikācijai.",
        formTitle: "Verifikācijas saite",
        formSubtitle: "Noklikšķini uz saites e-pastā, kas nosūtīts uz {{identifier}}",
        resendButton: "Nosūtīt saiti vēlreiz",
        successMessage: "E-pasts {{identifier}} ir pievienots tavam kontam.",
      },
      removeResource: {
        ...enUS.userProfile.emailAddressPage.removeResource,
        title: "Noņemt e-pasta adresi",
        messageLine1: "{{identifier}} tiks noņemts no šī konta.",
        messageLine2: "Vairs nevarēsi pieteikties, izmantojot šo e-pasta adresi.",
        successMessage: "{{emailAddress}} ir noņemts no tava konta.",
      },
    },
    passwordPage: {
      ...enUS.userProfile.passwordPage,
      title__set: "Iestatīt paroli",
      title__update: "Atjaunināt paroli",
      successMessage__set: "Tava parole ir iestatīta.",
      successMessage__update: "Tava parole ir atjaunināta.",
      successMessage__signOutOfOtherSessions: "Visas citas ierīces ir izrakstītas.",
      checkboxInfoText__signOutOfOtherSessions: "Ieteicams izrakstīties no visām citām ierīcēm, kurās var būt izmantota vecā parole.",
      readonly: "Tava parole pašlaik nevar tikt rediģēta, jo vari pieteikties tikai ar uzņēmuma savienojumu.",
    },
    profilePage: {
      ...enUS.userProfile.profilePage,
      title: "Atjaunināt profilu",
      successMessage: "Tavs profils ir atjaunināts.",
      fileDropAreaHint: "Ieteicamais izmērs 1:1, līdz 10MB.",
      imageFormTitle: "Profila attēls",
      imageFormSubtitle: "Augšupielādēt",
      imageFormDestructiveActionSubtitle: "Noņemt",
      readonly: "Tavus profila datus nodrošina uzņēmuma savienojums un tos nevar rediģēt.",
    },
    deletePage: {
      ...enUS.userProfile.deletePage,
      title: "Dzēst kontu",
      messageLine1: "Vai esi pārliecināts, ka vēlies dzēst savu kontu? Daži dati var tikt saglabāti. Lai pieprasītu pilnu datu dzēšanu, lūdzu sazinieties ar atbalstu.",
      messageLine2: "Šī darbība ir pastāvīga un neatgriezeniska.",
      actionDescription: "Ieraksti \"Delete account\" zemāk, lai turpinātu.",
      confirm: "Dzēst kontu",
    },
  },

  organizationSwitcher: {
    ...enUS.organizationSwitcher,
    action__createOrganization: "Izveidot organizāciju",
    action__invitationAccept: "Pievienoties",
    action__manageOrganization: "Pārvaldīt",
    action__suggestionsAccept: "Pieteikties",
    notSelected: "Nav izvēlētas organizācijas",
    personalWorkspace: "Personīgais konts",
  },
};
