import type { StackPlanByLocale, StackPlanModel } from "./stackTypes";

const aiLv: StackPlanModel = {
  name: "AI Aģentu Eksperts",
  price: "149",
  tagline: "Augstvērtīgi AI risinājumi lieliem uzņēmumiem",
  earn: "800€–3 500€/mēn",
  color: "#f97316",
  glow: "249,115,22",
  courses: ["AI Balss Aģenti", "WhatsApp Automatizācija", "Izveido savu Aplikāciju ar AI"],
  stats: { lessons: 44, modules: 5, hours: "11h 50 min", students: 47 },
  learn: [
    "Izveidot AI balss aģentu, kas zvana klientiem tavā vietā",
    "Pievienot Latvijas tālruņa numuru aģentam",
    "Automatizēt klientu komunikāciju WhatsApp",
    "Veidot mobilās aplikācijas bez programmēšanas",
    "Uzrunāt augstvērtīgus klientus ar premium piedāvājumu",
    "Izveidot demo, kas pats pārdod pakalpojumu",
    "Saņemt 1:1 mentoringa sesijas",
    "Piekļūt privātajai ekspertu kopienai",
  ],
  skills: [
    "Kā izveidot portfolio ar demo aģentiem",
    "Kā uzrunāt augstvērtīgus klientus",
    "Kā sagatavot premium piedāvājumu",
    "1:1 mentorings (2× mēnesī)",
    "Privāta kopiena",
    "Aģentūras augšanas ceļvedis",
  ],
  modules: [
    {
      id: 1,
      title: "Ievads — AI Aģentu revolūcija Latvijā",
      duration: "52 min",
      free: true,
      lessons: [
        {
          id: "1.1",
          title: "Kā AI aģenti maina uzņēmumu darbību — un kā tu to pārdod",
          type: "video",
          duration: "12 min",
          free: true,
          description:
            "Uzzini, kā uzņēmumi Latvijā jau šobrīd izmanto AI aģentus zobārstniecībā, nekustamajā īpašumā un restorānos. Reāli piemēri ar cenām, ko speciālisti iekasē par šiem risinājumiem.",
        },
        { id: "1.2", title: "3 vispieprasītākie AI aģentu veidi uzņēmumiem", type: "video", duration: "14 min", free: false },
        { id: "1.3", title: "Rīku komplekts: Retell AI, ElevenLabs, n8n, Vonage", type: "text", duration: "10 min", free: false },
        { id: "1.4", title: "Pirmais projekts — reāls klients, reāla nauda", type: "video", duration: "16 min", free: false },
      ],
    },
    {
      id: 2,
      title: "AI Balss Aģenti — no nulles līdz darbojošam aģentam",
      duration: "3h 20 min",
      free: false,
      lessons: [
        { id: "2.1", title: "Retell AI platforma — konts un pirmais aģents", type: "video", duration: "22 min", free: false },
        { id: "2.2", title: "ElevenLabs — reālistiskas latviešu balss veidošana", type: "video", duration: "25 min", free: false },
        { id: "2.3", title: "Latvijas numura integrācija ar Vonage vai Twilio", type: "video", duration: "30 min", free: false },
        { id: "2.4", title: "Sarunu skripts un loģika — ko aģents saka", type: "video", duration: "28 min", free: false },
        { id: "2.5", title: "Google Calendar integrācija — automātiska rezervācija", type: "video", duration: "25 min", free: false },
        { id: "2.6", title: "Zvanu datu glabāšana CRM automātiski", type: "video", duration: "20 min", free: false },
        { id: "2.7", title: "Demo aģenta izveide pārdošanai klientam", type: "video", duration: "30 min", free: false },
      ],
    },
    {
      id: 3,
      title: "WhatsApp Automatizācija ar Make.com un n8n",
      duration: "2h 30 min",
      free: false,
      lessons: [
        { id: "3.1", title: "Make.com vai n8n — kuru izvēlēties un kāpēc", type: "video", duration: "18 min", free: false },
        { id: "3.2", title: "WhatsApp Business API iestatīšana", type: "video", duration: "25 min", free: false },
        { id: "3.3", title: "Automātisko atbilžu scenāriji — klientu jautājumi", type: "video", duration: "22 min", free: false },
        { id: "3.4", title: "Lead notifikācijas uz e-pastu un CRM", type: "video", duration: "20 min", free: false },
        { id: "3.5", title: "Latvijas klients — pilns piemērs no sākuma līdz beigām", type: "video", duration: "25 min", free: false },
        { id: "3.6", title: "Pārdot WhatsApp automatizāciju — cena un piedāvājums", type: "text", duration: "20 min", free: false },
      ],
    },
    {
      id: 4,
      title: "Izveido savu Aplikāciju ar AI",
      duration: "2h 40 min",
      free: false,
      lessons: [
        { id: "4.1", title: "Bolt.new un Lovable — AI aplikāciju veidošana bez koda", type: "video", duration: "22 min", free: false },
        { id: "4.2", title: "MVP no idejas 1 dienā — soli pa solim", type: "video", duration: "30 min", free: false },
        { id: "4.3", title: "Dizains ar AI — Figma un Framer", type: "video", duration: "25 min", free: false },
        { id: "4.4", title: "Backend bez koda — Supabase un Firebase", type: "video", duration: "22 min", free: false },
        { id: "4.5", title: "App Store un Google Play publicēšana", type: "video", duration: "20 min", free: false },
        { id: "4.6", title: "Pārdot aplikāciju klientam — €800–€3000 projekts", type: "text", duration: "21 min", free: false },
      ],
    },
    {
      id: 5,
      title: "Premium Bizness — Augstvērtīgi Klienti un Aģentūra",
      duration: "2h 28 min",
      free: false,
      lessons: [
        { id: "5.1", title: "Portfolio ar demo aģentiem — kā to uzbūvēt", type: "video", duration: "25 min", free: false },
        { id: "5.2", title: "Augstvērtīgu klientu uzrunāšana — LinkedIn + aukstie zvani", type: "video", duration: "22 min", free: false },
        { id: "5.3", title: "Premium cenu piedāvājums — ko iekļaut", type: "text", duration: "20 min", free: false },
        { id: "5.4", title: "1:1 mentorings — kā to izmantot efektīvi", type: "video", duration: "18 min", free: false },
        { id: "5.5", title: "No speciālista uz aģentūru — augšanas ceļvedis", type: "video", duration: "25 min", free: false },
        { id: "5.6", title: "Privātā kopiena — kā tīkloties un sadarboties", type: "video", duration: "18 min", free: false },
        { id: "5.7", title: "No €0 līdz €3000/mēn — 6 mēnešu plāns", type: "text", duration: "20 min", free: false },
      ],
    },
  ],
  heroPill: "🎙️ Premium plāns",
  heroBefore: "Izveido ",
  heroHighlight: "AI Aģentus",
  heroAfter: ", ko uzņēmumi maksā par tūkstošiem",
  lead: "Augstvērtīgi risinājumi — balss aģenti, WhatsApp automatizācija un mobilās aplikācijas. Plus mentorings un privāta kopiena.",
  topBarPlanLine: "AI Aģentu Eksperts · €149/mēn",
  earningRows: [
    { label: "2–3 klienti", amount: "€1 600–€4 500/mēn" },
    { label: "4–6 klienti", amount: "€3 200–€9 000/mēn" },
  ],
  includedCourses: [
    { icon: "🎙️", name: "AI Balss Aģenti", desc: "Automātiski zvani un pierakstu rezervācija" },
    { icon: "💬", name: "WhatsApp Automatizācija", desc: "Automātiskas atbildes un lead apstrāde" },
    { icon: "📱", name: "Izveido savu Aplikāciju ar AI", desc: "No idejas līdz darbojošai lietotnei" },
  ],
  ctaPrimary: "Sākt AI Aģentu Eksperta ceļu →",
  premiumBonuses: ["1:1 mentorings (2× mēnesī)", "Privāta kopiena", "Aģentūras augšanas ceļvedis"],
};

const aiEn: StackPlanModel = {
  ...aiLv,
  name: "AI Agent Specialist",
  tagline: "Premium conversational + automation retainers enterprises actually fund",
  earn: "€800–€3 500/mo",
  courses: ["AI voice operators", "WhatsApp automation", "AI-built micro apps"],
  learn: [
    "Ship voice agents that book, qualify, and hand off flawlessly",
    "Attach compliant Baltic numbering + failover routing",
    "Automate WhatsApp concierge flows with audited logs",
    "Prototype mobile apps overnight using AI scaffolding",
    "Sell executive-grade packages with CFO-friendly ROI math",
    "Let your demo agent pitch while you observe",
    "Tap 1:1 mentor sessions bundled in-plan",
    "Plug into the private builder community",
  ],
  skills: [
    "Portfolio design around live agent demos",
    "Enterprise discovery without buzzword bingo",
    "Premium proposal stacks + legal addenda",
    "1:1 mentoring cadence (2× monthly)",
    "Private mastermind + deal swap",
    "Agency roadmap from solo to pod model",
  ],
  heroPill: "🎙️ Premium track",
  heroBefore: "Build ",
  heroHighlight: "production AI agents",
  heroAfter: " buyers expense without committee drama",
  lead: "Voice, WhatsApp, and micro-app factories—paired with mentorship and a curated community backing premium pricing.",
  topBarPlanLine: "AI Agent Specialist · €149/mo",
  earningRows: [
    { label: "2–3 premium clients", amount: "€1 600–€4 500/mo" },
    { label: "4–6 premium clients", amount: "€3 200–€9 000/mo" },
  ],
  includedCourses: [
    { icon: "🎙️", name: "AI voice operators", desc: "Outbound/inbound concierge with guardrails" },
    { icon: "💬", name: "WhatsApp automation suites", desc: "Structured replies + CRM pushes" },
    { icon: "📱", name: "Micro apps via AI codegen", desc: "From napkin sketch to clickable pilot" },
  ],
  ctaPrimary: "Start the AI Agent Specialist path →",
  premiumBonuses: ["1:1 mentoring (twice monthly)", "Private operator community", "Agency scaling roadmap"],
  modules: [
    {
      id: 1,
      title: "Introduction — Latvia’s AI agent wave",
      duration: "52 min",
      free: true,
      lessons: [
        {
          id: "1.1",
          title: "How autonomous agents rewired SMB ops—and budgets",
          type: "video",
          duration: "12 min",
          free: true,
          description:
            "Clinics, hospitality, property teams already paying pilots—benchmark ticket sizes and timelines you can reference live.",
        },
        { id: "1.2", title: "Three agent archetypes enterprises request first", type: "video", duration: "14 min", free: false },
        { id: "1.3", title: "Retell AI, ElevenLabs, n8n, Vonage stack primer", type: "text", duration: "10 min", free: false },
        { id: "1.4", title: "Deal recap: invoice-ready project in weeks", type: "video", duration: "16 min", free: false },
      ],
    },
    {
      id: 2,
      title: "Voice agents — rehearsal to production SIP",
      duration: "3h 20 min",
      free: false,
      lessons: [
        { id: "2.1", title: "Retell AI workspaces + failover testing", type: "video", duration: "22 min", free: false },
        { id: "2.2", title: "ElevenLabs Latvian-ish voice clones", type: "video", duration: "25 min", free: false },
        { id: "2.3", title: "Vonage / Twilio +371 numbering walkthrough", type: "video", duration: "30 min", free: false },
        { id: "2.4", title: "Dialogue scripting + escalation trees", type: "video", duration: "28 min", free: false },
        { id: "2.5", title: "Calendar syncing + SLA buffers", type: "video", duration: "25 min", free: false },
        { id: "2.6", title: "CRM ingestion from call payloads", type: "video", duration: "20 min", free: false },
        { id: "2.7", title: "Demo booth agent that pitches itself", type: "video", duration: "30 min", free: false },
      ],
    },
    {
      id: 3,
      title: "WhatsApp Automation with Make + n8n",
      duration: "2h 30 min",
      free: false,
      lessons: [
        { id: "3.1", title: "Choosing orchestration hubs for regulated chats", type: "video", duration: "18 min", free: false },
        { id: "3.2", title: "WhatsApp Business API provisioning", type: "video", duration: "25 min", free: false },
        { id: "3.3", title: "Intent branches + multilingual fallbacks", type: "video", duration: "22 min", free: false },
        { id: "3.4", title: "Lead alerts into email + CRM", type: "video", duration: "20 min", free: false },
        { id: "3.5", title: "End-to-end Baltic client simulation", type: "video", duration: "25 min", free: false },
        { id: "3.6", title: "Packaging uptime retainers confidently", type: "text", duration: "20 min", free: false },
      ],
    },
    {
      id: 4,
      title: "AI Micro Apps Clients Can Touch",
      duration: "2h 40 min",
      free: false,
      lessons: [
        { id: "4.1", title: "Bolt.new / Lovable rapid prototyping etiquette", type: "video", duration: "22 min", free: false },
        { id: "4.2", title: "Idea → MVP checklist in a day", type: "video", duration: "30 min", free: false },
        { id: "4.3", title: "AI-aided UX in Framer + FigJam rituals", type: "video", duration: "25 min", free: false },
        { id: "4.4", title: "Supabase/Firebase zero-code backends", type: "video", duration: "22 min", free: false },
        { id: "4.5", title: "App Store & Play publishing guardrails", type: "video", duration: "20 min", free: false },
        { id: "4.6", title: "€800–€3k project quoting patterns", type: "text", duration: "21 min", free: false },
      ],
    },
    {
      id: 5,
      title: "Premium Business — Whale Accounts + Agency Spine",
      duration: "2h 28 min",
      free: false,
      lessons: [
        { id: "5.1", title: "Demo libraries that resemble live prod", type: "video", duration: "25 min", free: false },
        { id: "5.2", title: "High-trust outbound: LinkedIn + warm calls", type: "video", duration: "22 min", free: false },
        { id: "5.3", title: "Board-ready proposals + DPIA appendix", type: "text", duration: "20 min", free: false },
        { id: "5.4", title: "Using bundled mentorship strategically", type: "video", duration: "18 min", free: false },
        { id: "5.5", title: "Solo builder → pods without chaos", type: "video", duration: "25 min", free: false },
        { id: "5.6", title: "Networking inside private collective", type: "video", duration: "18 min", free: false },
        { id: "5.7", title: "0 → €3k/month six-month operating plan", type: "text", duration: "20 min", free: false },
      ],
    },
  ],
};

export const aiAgentStack: StackPlanByLocale = { lv: aiLv, en: aiEn };
