import type { StackPlanByLocale, StackPlanModel } from "./stackTypes";

const digitalaisLv: StackPlanModel = {
  name: "AI Biznesa Automatizācija",
  price: "59",
  tagline: "Uzbūvē AI mājaslapas ar Claude Code un AI asistentus, kas strādā biznesa vietā",
  earn: "500€–1 800€/mēn",
  color: "#00ff88",
  glow: "0,255,136",
  courses: ["AI Mājaslapa", "Claude Code", "AI asistenti", "AI biznesa funkcijas"],
  stats: { lessons: 41, modules: 6, hours: "13h 9 min", students: 89 },
  learn: [
    "Saprast, kāpēc AI pilnībā mainīja mājaslapu izstrādi",
    "Uzbūvēt īstu mājaslapu ar Claude Code — bez programmēšanas pieredzes",
    "Padarīt dizainu premium un publicēt lapu tiešsaistē",
    "Izveidot AI personīgos asistentus ar Claude — sev un biznesiem",
    "Iedot asistentam uzņēmuma zināšanas, instrukcijas un failus",
    "Automatizēt atkārtoto ikdienas darbu un dokumentu apstrādi",
    "Būvēt asistentus mārketingam, pārdošanai un klientu atbalstam",
    "Integrēt kontaktformas, e-pastus un biznesa automatizācijas",
    "Izveidot profesionālu portfolio ar reāliem darbiem",
    "Pārdot AI asistentus biznesiem kā augstas vērtības pakalpojumu",
    "Pārvērst šo prasmi reālā biznesā — 500€–1800€ mēnesī",
  ],
  skills: [
    "Mājaslapas būvēšana ar Claude Code no nulles",
    "AI personīgie asistenti ar Claude — sev un klientiem",
    "Zināšanu bāze, failu analīze un darba automatizācija",
    "Premium dizains, animācijas un AI vizuāļi",
    "AI čatbots, asistents un biznesa automatizācijas",
    "Domēns, publicēšana un projekta nodošana",
    "Klientu atrašana, cenu noteikšana un pārdošana",
  ],
  modules: [
    {
      id: 1,
      title: "AI revolūcija mājaslapu izstrādē",
      duration: "35 min",
      free: true,
      lessons: [
        {
          id: "1.1",
          title: "Kā AI pilnībā mainīja mājaslapu izstrādi",
          type: "video",
          duration: "10 min",
          free: true,
          description:
            "Pēdējos gados mājaslapu izstrāde mainījās pilnībā. Tas, kas agrāk prasīja nedēļas darba un dārgu izstrādātāju komandu, šodien ir izdarāms stundās. Šajā nodarbībā saproti, kāpēc tieši tagad ir labākais brīdis iemācīties būvēt mājaslapas ar AI.",
        },
        {
          id: "1.2",
          title: "Kāpēc biznesiem vairs nevajag mēnešus un izstrādātāju komandu",
          type: "video",
          duration: "9 min",
          free: true,
          description:
            "Kāpēc uzņēmumi vairs nemaksā tūkstošiem eiro par mēnešiem ilgu izstrādi — un kā tas paver iespēju tev kļūt par speciālistu, kas piegādā ātrāk un lētāk.",
        },
        { id: "1.3", title: "Claude Code — kāpēc tas maina visu", type: "video", duration: "8 min", free: false },
        { id: "1.4", title: "Ko tu uzbūvēsi šajā kursā (un kā kļūt par pakalpojumu)", type: "video", duration: "8 min", free: false },
      ],
    },
    {
      id: 2,
      title: "AI mājaslapas būvēšana ar Claude Code",
      duration: "2h 40 min",
      free: false,
      lessons: [
        { id: "2.1", title: "Claude Code instalēšana un sagatavošana", type: "video", duration: "18 min", free: false },
        { id: "2.2", title: "Pirmais projekts — sākam no nulles", type: "video", duration: "22 min", free: false },
        { id: "2.3", title: "Claude Code darba plūsma — kā strādāt efektīvi", type: "video", duration: "24 min", free: false },
        { id: "2.4", title: "Efektīvi prompti — kā runāt ar Claude Code", type: "video", duration: "25 min", free: false },
        { id: "2.5", title: "Sākumlapas būvēšana soli pa solim", type: "video", duration: "26 min", free: false },
        { id: "2.6", title: "Sadaļas un izkārtojumi", type: "video", duration: "23 min", free: false },
        { id: "2.7", title: "Responsīvs dizains — pielāgošana visām ierīcēm", type: "video", duration: "22 min", free: false },
      ],
    },
    {
      id: 3,
      title: "Dizaina uzlabošana un publicēšana",
      duration: "2h",
      free: false,
      lessons: [
        { id: "3.1", title: "Kā padarīt dizainu premium", type: "video", duration: "22 min", free: false },
        { id: "3.2", title: "Moderni UI & UX uzlabojumi", type: "video", duration: "22 min", free: false },
        { id: "3.3", title: "Attēli un AI ģenerēti vizuāļi", type: "video", duration: "20 min", free: false },
        { id: "3.4", title: "Animācijas un mikrointerakcijas", type: "video", duration: "18 min", free: false },
        { id: "3.5", title: "Sava domēna pieslēgšana", type: "video", duration: "16 min", free: false },
        { id: "3.6", title: "Mājaslapas publicēšana tiešsaistē", type: "video", duration: "22 min", free: false },
      ],
    },
    {
      id: 4,
      title: "AI funkcijas biznesiem",
      duration: "2h",
      free: false,
      lessons: [
        { id: "4.1", title: "AI čatbota integrācija mājaslapā", type: "video", duration: "22 min", free: false },
        { id: "4.2", title: "AI mājaslapas asistents", type: "video", duration: "20 min", free: false },
        { id: "4.3", title: "Kontaktformas un pieteikumi", type: "video", duration: "18 min", free: false },
        { id: "4.4", title: "Biznesa automatizācijas", type: "video", duration: "22 min", free: false },
        { id: "4.5", title: "E-pasta integrācijas", type: "video", duration: "18 min", free: false },
        { id: "4.6", title: "Reāli biznesa piemēri", type: "video", duration: "20 min", free: false },
      ],
    },
    {
      id: 5,
      title: "AI personīgie asistenti ar Claude",
      duration: "3h 54 min",
      free: false,
      lessons: [
        {
          id: "5.1",
          title: "Kas ir AI personīgais asistents?",
          type: "video",
          duration: "12 min",
          free: false,
          description:
            "AI asistents nav tikai čats. Tas ir digitāls darbinieks, kuram iedod uzņēmuma zināšanas, instrukcijas un failus — un kurš pēc tam strādā 24/7, neprasot algu. Šajā nodarbībā saproti, ar ko asistents atšķiras no parasta čatbota un kur tam ir vislielākā vērtība biznesā.",
        },
        { id: "5.2", title: "Pirmā Claude AI asistenta izveide", type: "video", duration: "20 min", free: false },
        { id: "5.3", title: "Kā asistentam iedot zināšanas un instrukcijas", type: "video", duration: "22 min", free: false },
        { id: "5.4", title: "Darbs ar PDF, Word un Excel failiem", type: "video", duration: "24 min", free: false },
        { id: "5.5", title: "Asistenti dažādiem biznesiem", type: "video", duration: "20 min", free: false },
        { id: "5.6", title: "Mārketinga asistents", type: "video", duration: "18 min", free: false },
        { id: "5.7", title: "Klientu atbalsta asistents", type: "video", duration: "18 min", free: false },
        { id: "5.8", title: "Pārdošanas asistents", type: "video", duration: "18 min", free: false },
        { id: "5.9", title: "Uzņēmuma iekšējo zināšanu asistents", type: "video", duration: "22 min", free: false },
        { id: "5.10", title: "Ikdienas produktivitātes asistents", type: "video", duration: "18 min", free: false },
        { id: "5.11", title: "Asistenta testēšana un uzlabošana", type: "video", duration: "20 min", free: false },
        { id: "5.12", title: "AI asistentu iepakošana un pārdošana kā pakalpojums", type: "video", duration: "22 min", free: false },
      ],
    },
    {
      id: 6,
      title: "Portfolio, klienti un pārdošana",
      duration: "2h",
      free: false,
      lessons: [
        { id: "6.1", title: "Profesionāla portfolio izveide", type: "video", duration: "22 min", free: false },
        { id: "6.2", title: "Kā noteikt cenu savam pakalpojumam", type: "video", duration: "20 min", free: false },
        { id: "6.3", title: "Pirmo klientu atrašana", type: "video", duration: "20 min", free: false },
        { id: "6.4", title: "Outreach veidnes un ziņojumi", type: "text", duration: "18 min", free: false },
        { id: "6.5", title: "Projektu profesionāla nodošana", type: "video", duration: "20 min", free: false },
        { id: "6.6", title: "Kā izaudzēt reālu biznesu", type: "video", duration: "20 min", free: false },
      ],
    },
  ],
  heroPill: "⭐ Populārākais plāns",
  heroBefore: "Uzbūvē ",
  heroHighlight: "AI mājaslapas un AI asistentus",
  heroAfter: " un pārdod tos biznesiem",
  lead: "Divas prasmes vienā pakā: īsta mājaslapa, ko uzbūvē ar Claude Code un publicē tiešsaistē, un AI asistents, kas atbild uz jautājumiem no uzņēmuma zināšanām, analizē dokumentus un automatizē ikdienas darbu. Praktiski no pirmās nodarbības.",
  topBarPlanLine: "AI Biznesa Automatizācija · €59/mēn",
  earningRows: [
    { label: "2–3 klienti", amount: "€1 000–€3 600/mēn" },
    { label: "4–6 klienti", amount: "€2 000–€7 200/mēn" },
  ],
  includedCourses: [
    { icon: "🌐", name: "AI Mājaslapa", desc: "Būvēšana ar Claude Code, premium dizains, publicēšana" },
    { icon: "🧠", name: "AI asistenti", desc: "Zināšanu bāze, failu analīze, asistenti biznesiem" },
    { icon: "🤖", name: "AI funkcijas", desc: "Čatbots, asistents, automatizācijas un e-pasti" },
    { icon: "💼", name: "Bizness & klienti", desc: "Portfolio, cenas, outreach un projektu nodošana" },
  ],
  ctaPrimary: "Sākt AI Biznesa Automatizācijas ceļu →",
};

const digitalaisEn: StackPlanModel = {
  ...digitalaisLv,
  name: "AI Business Automation",
  tagline: "Build AI websites with Claude Code and AI assistants that work in a business's place",
  earn: "€500–€1,800/mo",
  courses: ["AI website", "Claude Code", "AI assistants", "AI business features"],
  learn: [
    "Understand why AI completely changed website development",
    "Build a real website with Claude Code — no coding experience needed",
    "Make the design premium and publish the site online",
    "Build AI personal assistants with Claude — for yourself and for businesses",
    "Give an assistant company knowledge, instructions, and files",
    "Automate repetitive daily work and document handling",
    "Build assistants for marketing, sales, and customer support",
    "Integrate contact forms, emails, and business automations",
    "Build a professional portfolio with real work",
    "Sell AI assistants to businesses as a high-value service",
    "Turn this skill into a real business — €500–€1,800/month",
  ],
  skills: [
    "Building websites with Claude Code from scratch",
    "AI personal assistants with Claude — for you and for clients",
    "Knowledge bases, file analysis, and work automation",
    "Premium design, animations, and AI visuals",
    "AI chatbot, assistant, and business automations",
    "Domain, publishing, and professional handoff",
    "Finding clients, pricing, and selling the service",
  ],
  heroPill: "⭐ Most popular plan",
  heroBefore: "Build ",
  heroHighlight: "AI websites and AI assistants",
  heroAfter: " and sell them to businesses",
  lead: "Two skills in one package: a real website you build with Claude Code and publish online, and an AI assistant that answers questions from company knowledge, analyses documents, and automates daily work. Practical from the very first lesson.",
  topBarPlanLine: "AI Business Automation · €59/mo",
  earningRows: [
    { label: "2–3 clients", amount: "€1,000–€3,600/mo" },
    { label: "4–6 clients", amount: "€2,000–€7,200/mo" },
  ],
  includedCourses: [
    { icon: "🌐", name: "AI website", desc: "Built with Claude Code, premium design, publishing" },
    { icon: "🧠", name: "AI assistants", desc: "Knowledge bases, file analysis, assistants for businesses" },
    { icon: "🤖", name: "AI features", desc: "Chatbot, assistant, automations, and emails" },
    { icon: "💼", name: "Business & clients", desc: "Portfolio, pricing, outreach, and handoff" },
  ],
  ctaPrimary: "Start the AI Business Automation path →",
  modules: [
    {
      id: 1,
      title: "The AI revolution in website development",
      duration: "35 min",
      free: true,
      lessons: [
        {
          id: "1.1",
          title: "How AI completely changed website development",
          type: "video",
          duration: "10 min",
          free: true,
          description:
            "In just a few years website development changed completely. What used to take weeks of work and an expensive dev team can now be done in hours. This lesson shows why right now is the best time to learn to build websites with AI.",
        },
        {
          id: "1.2",
          title: "Why businesses no longer need months or a dev team",
          type: "video",
          duration: "9 min",
          free: true,
          description:
            "Why companies no longer pay thousands for months-long builds — and how that opens the door for you to deliver faster and cheaper.",
        },
        { id: "1.3", title: "Claude Code — why it changes everything", type: "video", duration: "8 min", free: false },
        { id: "1.4", title: "What you'll build in this course (and how to sell it)", type: "video", duration: "8 min", free: false },
      ],
    },
    {
      id: 2,
      title: "Building an AI website with Claude Code",
      duration: "2h 40 min",
      free: false,
      lessons: [
        { id: "2.1", title: "Installing and setting up Claude Code", type: "video", duration: "18 min", free: false },
        { id: "2.2", title: "Creating your first project from scratch", type: "video", duration: "22 min", free: false },
        { id: "2.3", title: "The Claude Code workflow — working efficiently", type: "video", duration: "24 min", free: false },
        { id: "2.4", title: "Writing effective prompts for Claude Code", type: "video", duration: "25 min", free: false },
        { id: "2.5", title: "Building the homepage step by step", type: "video", duration: "26 min", free: false },
        { id: "2.6", title: "Sections and layouts", type: "video", duration: "23 min", free: false },
        { id: "2.7", title: "Responsive design for every device", type: "video", duration: "22 min", free: false },
      ],
    },
    {
      id: 3,
      title: "Improving the design & publishing",
      duration: "2h",
      free: false,
      lessons: [
        { id: "3.1", title: "Making the design look premium", type: "video", duration: "22 min", free: false },
        { id: "3.2", title: "Modern UI & UX improvements", type: "video", duration: "22 min", free: false },
        { id: "3.3", title: "Images and AI-generated visuals", type: "video", duration: "20 min", free: false },
        { id: "3.4", title: "Animations and micro-interactions", type: "video", duration: "18 min", free: false },
        { id: "3.5", title: "Connecting a custom domain", type: "video", duration: "16 min", free: false },
        { id: "3.6", title: "Publishing the website online", type: "video", duration: "22 min", free: false },
      ],
    },
    {
      id: 4,
      title: "AI features for businesses",
      duration: "2h",
      free: false,
      lessons: [
        { id: "4.1", title: "AI chatbot integration", type: "video", duration: "22 min", free: false },
        { id: "4.2", title: "On-site AI website assistant", type: "video", duration: "20 min", free: false },
        { id: "4.3", title: "Contact forms and inquiries", type: "video", duration: "18 min", free: false },
        { id: "4.4", title: "Business automations", type: "video", duration: "22 min", free: false },
        { id: "4.5", title: "Email integrations", type: "video", duration: "18 min", free: false },
        { id: "4.6", title: "Real business examples", type: "video", duration: "20 min", free: false },
      ],
    },
    {
      id: 5,
      title: "AI personal assistants with Claude",
      duration: "3h 54 min",
      free: false,
      lessons: [
        {
          id: "5.1",
          title: "What is an AI personal assistant?",
          type: "video",
          duration: "12 min",
          free: false,
          description:
            "An AI assistant is more than a chat window. It's a digital employee you give company knowledge, instructions, and files to — and it then works 24/7 without asking for a salary. This lesson covers how an assistant differs from a plain chatbot, and where it creates the most value in a business.",
        },
        { id: "5.2", title: "Creating your first Claude AI assistant", type: "video", duration: "20 min", free: false },
        { id: "5.3", title: "Giving your assistant knowledge and instructions", type: "video", duration: "22 min", free: false },
        { id: "5.4", title: "Working with PDFs, Word files, and Excel", type: "video", duration: "24 min", free: false },
        { id: "5.5", title: "Creating assistants for different businesses", type: "video", duration: "20 min", free: false },
        { id: "5.6", title: "Marketing assistant", type: "video", duration: "18 min", free: false },
        { id: "5.7", title: "Customer support assistant", type: "video", duration: "18 min", free: false },
        { id: "5.8", title: "Sales assistant", type: "video", duration: "18 min", free: false },
        { id: "5.9", title: "Internal company knowledge assistant", type: "video", duration: "22 min", free: false },
        { id: "5.10", title: "Daily productivity assistant", type: "video", duration: "18 min", free: false },
        { id: "5.11", title: "Testing and improving your assistant", type: "video", duration: "20 min", free: false },
        { id: "5.12", title: "Packaging and selling AI assistants as a service", type: "video", duration: "22 min", free: false },
      ],
    },
    {
      id: 6,
      title: "Portfolio, clients & selling your service",
      duration: "2h",
      free: false,
      lessons: [
        { id: "6.1", title: "Building a professional portfolio", type: "video", duration: "22 min", free: false },
        { id: "6.2", title: "Pricing your service", type: "video", duration: "20 min", free: false },
        { id: "6.3", title: "Finding your first clients", type: "video", duration: "20 min", free: false },
        { id: "6.4", title: "Outreach templates and messages", type: "text", duration: "18 min", free: false },
        { id: "6.5", title: "Delivering projects professionally", type: "video", duration: "20 min", free: false },
        { id: "6.6", title: "Growing this into a real business", type: "video", duration: "20 min", free: false },
      ],
    },
  ],
};

export const digitalaisStack: StackPlanByLocale = { lv: digitalaisLv, en: digitalaisEn };
