import type { StackPlanByLocale, StackPlanModel } from "./stackTypes";

const digitalaisLv: StackPlanModel = {
  name: "Digitālais Speciālists",
  price: "59",
  tagline: "Izveido AI risinājumus biznesiem un pārdod tos par stabilu cenu",
  earn: "500€–1 800€/mēn",
  color: "#00ff88",
  glow: "0,255,136",
  courses: ["Mājaslapa", "AI Asistenti", "AI Asistents uz E-pastiem"],
  stats: { lessons: 38, modules: 5, hours: "9h 20 min", students: 89 },
  learn: [
    "Izveidot profesionālu mājaslapa bez programmēšanas",
    "Pievienot AI chatbot, kas atbild 24/7",
    "Automatizēt e-pasta komunikāciju ar AI",
    "Uzrunāt klientus (aukstie zvani + DM)",
    "Sagatavot profesionālu pakalpojuma piedāvājumu",
    "Veidot ikmēneša atbalsta paketes uzņēmumiem",
    "Izveidot portfolio ar reāliem darbiem",
    "Nopelnīt 500€–1800€ mēnesī kā Digitālais Speciālists",
  ],
  skills: [
    "Kā izveidot portfolio ar reāliem darbiem",
    "Kā uzrunāt klientus (aukstie zvani + DM)",
    "Kā sagatavot profesionālu piedāvājumu",
    "Klientu onboarding process",
    "Ikmēneša atbalsta paketes",
  ],
  modules: [
    {
      id: 1,
      title: "Ievads — Ko nozīmē būt Digitālajam Speciālistam",
      duration: "44 min",
      free: true,
      lessons: [
        {
          id: "1.1",
          title: "Kā uzņēmumi maksā par digitālajiem pakalpojumiem",
          type: "video",
          duration: "10 min",
          free: true,
          description:
            "Uzzini, kāpēc vietējie uzņēmumi arvien vairāk meklē digitālos speciālistus un cik viņi ir gatavi maksāt. Reāli piemēri no Latvijas tirgus — frizētavas, zobārsti, restorāni.",
        },
        { id: "1.2", title: "3 pakalpojumi, ko var pārdot uzreiz (bez pieredzes)", type: "video", duration: "12 min", free: false },
        { id: "1.3", title: "Rīku komplekts iesācējam — ko izmantot", type: "text", duration: "8 min", free: false },
        { id: "1.4", title: "Pirmais klients — reāls piemērs no Rīgas", type: "video", duration: "14 min", free: false },
      ],
    },
    {
      id: 2,
      title: "Mājaslapa — no nulles līdz publicēšanai",
      duration: "2h 40 min",
      free: false,
      lessons: [
        { id: "2.1", title: "Rīku izvēle: Framer, Webflow vai Cursor", type: "video", duration: "20 min", free: false },
        { id: "2.2", title: "Dizaina principi bez pieredzes — ko uzmanīties", type: "video", duration: "25 min", free: false },
        { id: "2.3", title: "Satura struktūra — kā izklāstīt uzņēmuma informāciju", type: "video", duration: "22 min", free: false },
        { id: "2.4", title: "SEO pamati — Google meklēšana un atslēgvārdi", type: "video", duration: "20 min", free: false },
        { id: "2.5", title: "Mobilā versija — pielāgošana visām ierīcēm", type: "video", duration: "18 min", free: false },
        { id: "2.6", title: "Domēns, hostings un publicēšana", type: "video", duration: "15 min", free: false },
        { id: "2.7", title: "Projekta nodošana klientam + rēķins", type: "text", duration: "20 min", free: false },
      ],
    },
    {
      id: 3,
      title: "AI Asistenti — mājaslapa & sociālie tīkli",
      duration: "2h 30 min",
      free: false,
      lessons: [
        { id: "3.1", title: "Voiceflow iestatīšana — pamati 30 minūtēs", type: "video", duration: "22 min", free: false },
        { id: "3.2", title: "Sarunu loģika: jautājumi, atbildes, scenāriji", type: "video", duration: "25 min", free: false },
        { id: "3.3", title: "Mājaslapa integrācija — 1 koda rinda", type: "video", duration: "18 min", free: false },
        { id: "3.4", title: "Virtuālais asistents Instagram & Facebook DM", type: "video", duration: "20 min", free: false },
        { id: "3.5", title: "WhatsApp bots — automātiska klientu apkalpošana", type: "video", duration: "18 min", free: false },
        { id: "3.6", title: "Lead vākšana automātiski — veidlapas un e-pasts", type: "video", duration: "20 min", free: false },
        { id: "3.7", title: "Chatbot testēšana un uzlabošana", type: "video", duration: "15 min", free: false },
        { id: "3.8", title: "Pārdot AI asistentu klientam — kā pamatot cenu", type: "text", duration: "12 min", free: false },
      ],
    },
    {
      id: 4,
      title: "AI Asistents uz E-pastiem",
      duration: "1h 50 min",
      free: false,
      lessons: [
        { id: "4.1", title: "Claude kā darba rīks — kas tas ir un kā darbojas", type: "video", duration: "15 min", free: false },
        { id: "4.2", title: "E-pasta veidnes: jauns klients, atbilde, atgādinājums", type: "text", duration: "20 min", free: false },
        { id: "4.3", title: "Dizaina briifi un projekta apraksti ar AI", type: "video", duration: "18 min", free: false },
        { id: "4.4", title: "Satura ģenerēšana sociālajiem tīkliem", type: "video", duration: "20 min", free: false },
        { id: "4.5", title: "Ikdienas darbu automatizācija — 10 piemēri", type: "text", duration: "17 min", free: false },
        { id: "4.6", title: "Pārdot AI asistenta pakalpojumu klientam", type: "video", duration: "20 min", free: false },
      ],
    },
    {
      id: 5,
      title: "Bizness, Portfolio un Klienti",
      duration: "1h 56 min",
      free: false,
      lessons: [
        { id: "5.1", title: "Portfolio ar reāliem darbiem — kā to uzbūvēt", type: "video", duration: "22 min", free: false },
        { id: "5.2", title: "Aukstie zvani + DM — veidnes un piemēri", type: "text", duration: "18 min", free: false },
        { id: "5.3", title: "Profesionāls cenu piedāvājums — ko iekļaut", type: "video", duration: "20 min", free: false },
        { id: "5.4", title: "Klientu onboarding process — soli pa solim", type: "video", duration: "20 min", free: false },
        { id: "5.5", title: "Ikmēneša atbalsta pakete — kā pārdot atkārtoti", type: "video", duration: "16 min", free: false },
        { id: "5.6", title: "No €0 līdz €1000/mēn — 90 dienu plāns", type: "text", duration: "20 min", free: false },
      ],
    },
  ],
  heroPill: "⭐ Populārākais plāns",
  heroBefore: "Izveido ",
  heroHighlight: "AI risinājumus",
  heroAfter: " biznesiem un pārdod tos",
  lead: "3 kursi vienā paketē — mājaslapa, chatbot un e-pasta automatizācija. Kompletā prasme pakete Latvijas digitālajam speciālistam.",
  topBarPlanLine: "Digitālais Speciālists · €59/mēn",
  earningRows: [
    { label: "2–3 klienti", amount: "€1 000–€3 600/mēn" },
    { label: "4–6 klienti", amount: "€2 000–€7 200/mēn" },
  ],
  includedCourses: [
    { icon: "🌐", name: "Mājaslapa", desc: "AI dizains, SEO, mobilā versija" },
    { icon: "💬", name: "AI Asistenti", desc: "Chatboti mājas lapai, Instagram, Facebook & WhatsApp" },
    { icon: "🤖", name: "AI Asistents uz E-pastiem", desc: "Automatizēti e-pasti un komunikācija" },
  ],
  ctaPrimary: "Sākt Digitālā Speciālista ceļu →",
};

const digitalaisEn: StackPlanModel = {
  ...digitalaisLv,
  name: "Digital Builder",
  tagline: "Ship AI-assisted digital services SMBs renew every month",
  earn: "€500–€1 800/mo",
  courses: ["Landing sites", "AI assistants", "AI inbox copilots"],
  learn: [
    "Launch credible marketing sites without writing code",
    "Embed multilingual chatbots that qualify leads overnight",
    "Automate outbound + inbox workflows with Claude-style stacks",
    "Prospect politely (cold call + DM systems)",
    "Package statements of work buyers actually sign",
    "Productize retainers your clients budget for yearly",
    "Showcase shipped work—even if you started last month",
    "Earn €500–€1 800/month as a Digital Builder",
  ],
  skills: [
    "Portfolio sequencing that proves delivery",
    "Cold call + DM templates with reply context",
    "Proposal sections legal teams expect",
    "Client onboarding rituals that reduce churn",
    "Monthly care packages priced for Baltic SMBs",
  ],
  heroPill: "⭐ Most popular bundle",
  heroBefore: "Build ",
  heroHighlight: "AI-native digital services",
  heroAfter: " businesses pay for monthly",
  lead: "Three accelerators bundled—sites, chatbots, inbox automation—a complete playbook for Latvian builders selling abroad too.",
  topBarPlanLine: "Digital Builder · €59/mo",
  earningRows: [
    { label: "2–3 retainers", amount: "€1 000–€3 600/mo" },
    { label: "4–6 retainers", amount: "€2 000–€7 200/mo" },
  ],
  includedCourses: [
    { icon: "🌐", name: "Landing + site systems", desc: "AI layout, SEO baselines, responsive QA" },
    { icon: "💬", name: "AI assistants", desc: "Website, Instagram, Facebook & WhatsApp bots" },
    { icon: "🤖", name: "AI inbox assistant", desc: "Automations for sales + ops mailboxes" },
  ],
  ctaPrimary: "Start the Digital Builder path →",
  modules: [
    {
      id: 1,
      title: "Introduction — Being a Digital Builder",
      duration: "44 min",
      free: true,
      lessons: [
        {
          id: "1.1",
          title: "How SMBs budget for AI-enabled partners",
          type: "video",
          duration: "10 min",
          free: true,
          description:
            "Why salons, dentists, and retail teams buy lightweight digital squads—with EU pricing references you can cite on calls.",
        },
        { id: "1.2", title: "Three monetizable stacks you can sell this week", type: "video", duration: "12 min", free: false },
        { id: "1.3", title: "Starter toolkit (free tiers + essentials)", type: "text", duration: "8 min", free: false },
        { id: "1.4", title: "First Baltic client teardown", type: "video", duration: "14 min", free: false },
      ],
    },
    {
      id: 2,
      title: "Websites — zero to deployed",
      duration: "2h 40 min",
      free: false,
      lessons: [
        { id: "2.1", title: "Choosing Framer, Webflow, or Cursor-led flows", type: "video", duration: "20 min", free: false },
        { id: "2.2", title: "Design fundamentals if you skipped art school", type: "video", duration: "25 min", free: false },
        { id: "2.3", title: "Structuring storytelling for skeptical owners", type: "video", duration: "22 min", free: false },
        { id: "2.4", title: "SEO scaffolding + keyword intent", type: "video", duration: "20 min", free: false },
        { id: "2.5", title: "Responsive QA checklist", type: "video", duration: "18 min", free: false },
        { id: "2.6", title: "Domains, hosting, launches without drama", type: "video", duration: "15 min", free: false },
        { id: "2.7", title: "Handoff memo + invoicing etiquette", type: "text", duration: "20 min", free: false },
      ],
    },
    {
      id: 3,
      title: "AI Assistants — website & social channels",
      duration: "2h 30 min",
      free: false,
      lessons: [
        { id: "3.1", title: "Voiceflow bootcamp in thirty minutes", type: "video", duration: "22 min", free: false },
        { id: "3.2", title: "Dialogue branching that feels human", type: "video", duration: "25 min", free: false },
        { id: "3.3", title: "One-line embeds for marketing sites", type: "video", duration: "18 min", free: false },
        { id: "3.4", title: "Instagram & Facebook DM virtual assistants", type: "video", duration: "20 min", free: false },
        { id: "3.5", title: "WhatsApp bots for 24/7 customer service", type: "video", duration: "18 min", free: false },
        { id: "3.6", title: "Capturing CRM-ready leads automatically", type: "video", duration: "20 min", free: false },
        { id: "3.7", title: "Testing matrix before go-live", type: "video", duration: "15 min", free: false },
        { id: "3.8", title: "Packaging ROI for AI assistant upgrades", type: "text", duration: "12 min", free: false },
      ],
    },
    {
      id: 4,
      title: "AI Copilots For Email Ops",
      duration: "1h 50 min",
      free: false,
      lessons: [
        { id: "4.1", title: "Claude as teammate — operating rules", type: "video", duration: "15 min", free: false },
        { id: "4.2", title: "Template vault: intake, objections, reminders", type: "text", duration: "20 min", free: false },
        { id: "4.3", title: "Creative brief drafting with guardrails", type: "video", duration: "18 min", free: false },
        { id: "4.4", title: "Social captions + repurposing loops", type: "video", duration: "20 min", free: false },
        { id: "4.5", title: "10 automations shaving admin hours weekly", type: "text", duration: "17 min", free: false },
        { id: "4.6", title: "Pitching assistants as infrastructure", type: "video", duration: "20 min", free: false },
      ],
    },
    {
      id: 5,
      title: "Pipeline, Portfolio, Expansion",
      duration: "1h 56 min",
      free: false,
      lessons: [
        { id: "5.1", title: "Case-study portfolios that aren’t fluff", type: "video", duration: "22 min", free: false },
        { id: "5.2", title: "Cold outbound scripts with proof hooks", type: "text", duration: "18 min", free: false },
        { id: "5.3", title: "Proposals procurement teams skim fast", type: "video", duration: "20 min", free: false },
        { id: "5.4", title: "Onboarding playbooks minimizing refunds", type: "video", duration: "20 min", free: false },
        { id: "5.5", title: "Recurring retainers + upsells", type: "video", duration: "16 min", free: false },
        { id: "5.6", title: "0 → €1000 MRR sprint (ninety-day map)", type: "text", duration: "20 min", free: false },
      ],
    },
  ],
};

export const digitalaisStack: StackPlanByLocale = { lv: digitalaisLv, en: digitalaisEn };
