import type { StackPlanByLocale, StackPlanModel } from "./stackTypes";

const digitalaisLv: StackPlanModel = {
  name: "Digitālais Speciālists",
  price: "59",
  tagline: "Uzbūvē īstu AI mājaslapu ar Claude Code un pārdod to biznesiem",
  earn: "500€–1 800€/mēn",
  color: "#00ff88",
  glow: "0,255,136",
  courses: ["AI Mājaslapa", "Claude Code", "AI biznesa funkcijas"],
  stats: { lessons: 29, modules: 5, hours: "9h 15 min", students: 89 },
  learn: [
    "Saprast, kāpēc AI pilnībā mainīja mājaslapu izstrādi",
    "Uzbūvēt īstu mājaslapu ar Claude Code — bez programmēšanas pieredzes",
    "Padarīt dizainu premium un publicēt lapu tiešsaistē",
    "Pievienot AI čatbotu un mājaslapas asistentu",
    "Integrēt kontaktformas, e-pastus un biznesa automatizācijas",
    "Izveidot profesionālu portfolio ar reāliem darbiem",
    "Atrast pirmos klientus un noteikt pareizo cenu",
    "Pārvērst šo prasmi reālā biznesā — 500€–1800€ mēnesī",
  ],
  skills: [
    "Mājaslapas būvēšana ar Claude Code no nulles",
    "Premium dizains, animācijas un AI vizuāļi",
    "AI čatbots, asistents un biznesa automatizācijas",
    "Domēns, publicēšana un projekta nodošana",
    "Klientu atrašana, cenu noteikšana un pārdošana",
  ],
  modules: [
    {
      id: 1,
      title: "AI revolūcija mājaslapu izstrādē",
      duration: "35 min",
      free: true,
      lessons: [
        {
          id: "1.1",
          title: "Kā AI pilnībā mainīja mājaslapu izstrādi",
          type: "video",
          duration: "10 min",
          free: true,
          description:
            "Pēdējos gados mājaslapu izstrāde mainījās pilnībā. Tas, kas agrāk prasīja nedēļas darba un dārgu izstrādātāju komandu, šodien ir izdarāms stundās. Šajā nodarbībā saproti, kāpēc tieši tagad ir labākais brīdis iemācīties būvēt mājaslapas ar AI.",
        },
        {
          id: "1.2",
          title: "Kāpēc biznesiem vairs nevajag mēnešus un izstrādātāju komandu",
          type: "video",
          duration: "9 min",
          free: true,
          description:
            "Kāpēc uzņēmumi vairs nemaksā tūkstošiem eiro par mēnešiem ilgu izstrādi — un kā tas paver iespēju tev kļūt par speciālistu, kas piegādā ātrāk un lētāk.",
        },
        { id: "1.3", title: "Claude Code — kāpēc tas maina visu", type: "video", duration: "8 min", free: false },
        { id: "1.4", title: "Ko tu uzbūvēsi šajā kursā (un kā kļūt par pakalpojumu)", type: "video", duration: "8 min", free: false },
      ],
    },
    {
      id: 2,
      title: "AI mājaslapas būvēšana ar Claude Code",
      duration: "2h 40 min",
      free: false,
      lessons: [
        { id: "2.1", title: "Claude Code instalēšana un sagatavošana", type: "video", duration: "18 min", free: false },
        { id: "2.2", title: "Pirmais projekts — sākam no nulles", type: "video", duration: "22 min", free: false },
        { id: "2.3", title: "Claude Code darba plūsma — kā strādāt efektīvi", type: "video", duration: "24 min", free: false },
        { id: "2.4", title: "Efektīvi prompti — kā runāt ar Claude Code", type: "video", duration: "25 min", free: false },
        { id: "2.5", title: "Sākumlapas būvēšana soli pa solim", type: "video", duration: "26 min", free: false },
        { id: "2.6", title: "Sadaļas un izkārtojumi", type: "video", duration: "23 min", free: false },
        { id: "2.7", title: "Responsīvs dizains — pielāgošana visām ierīcēm", type: "video", duration: "22 min", free: false },
      ],
    },
    {
      id: 3,
      title: "Dizaina uzlabošana un publicēšana",
      duration: "2h",
      free: false,
      lessons: [
        { id: "3.1", title: "Kā padarīt dizainu premium", type: "video", duration: "22 min", free: false },
        { id: "3.2", title: "Moderni UI & UX uzlabojumi", type: "video", duration: "22 min", free: false },
        { id: "3.3", title: "Attēli un AI ģenerēti vizuāļi", type: "video", duration: "20 min", free: false },
        { id: "3.4", title: "Animācijas un mikrointerakcijas", type: "video", duration: "18 min", free: false },
        { id: "3.5", title: "Sava domēna pieslēgšana", type: "video", duration: "16 min", free: false },
        { id: "3.6", title: "Mājaslapas publicēšana tiešsaistē", type: "video", duration: "22 min", free: false },
      ],
    },
    {
      id: 4,
      title: "AI funkcijas biznesiem",
      duration: "2h",
      free: false,
      lessons: [
        { id: "4.1", title: "AI čatbota integrācija mājaslapā", type: "video", duration: "22 min", free: false },
        { id: "4.2", title: "AI mājaslapas asistents", type: "video", duration: "20 min", free: false },
        { id: "4.3", title: "Kontaktformas un pieteikumi", type: "video", duration: "18 min", free: false },
        { id: "4.4", title: "Biznesa automatizācijas", type: "video", duration: "22 min", free: false },
        { id: "4.5", title: "E-pasta integrācijas", type: "video", duration: "18 min", free: false },
        { id: "4.6", title: "Reāli biznesa piemēri", type: "video", duration: "20 min", free: false },
      ],
    },
    {
      id: 5,
      title: "Portfolio, klienti un pārdošana",
      duration: "2h",
      free: false,
      lessons: [
        { id: "5.1", title: "Profesionāla portfolio izveide", type: "video", duration: "22 min", free: false },
        { id: "5.2", title: "Kā noteikt cenu savam pakalpojumam", type: "video", duration: "20 min", free: false },
        { id: "5.3", title: "Pirmo klientu atrašana", type: "video", duration: "20 min", free: false },
        { id: "5.4", title: "Outreach veidnes un ziņojumi", type: "text", duration: "18 min", free: false },
        { id: "5.5", title: "Projektu profesionāla nodošana", type: "video", duration: "20 min", free: false },
        { id: "5.6", title: "Kā izaudzēt reālu biznesu", type: "video", duration: "20 min", free: false },
      ],
    },
  ],
  heroPill: "⭐ Populārākais plāns",
  heroBefore: "Uzbūvē ",
  heroHighlight: "AI mājaslapas",
  heroAfter: " ar Claude Code un pārdod tās",
  lead: "No AI revolūcijas izpratnes līdz reālai mājaslapai, ko publicē tiešsaistē, papildina ar AI funkcijām un pārdod biznesiem. Praktiski no pirmās nodarbības.",
  topBarPlanLine: "Digitālais Speciālists · €59/mēn",
  earningRows: [
    { label: "2–3 klienti", amount: "€1 000–€3 600/mēn" },
    { label: "4–6 klienti", amount: "€2 000–€7 200/mēn" },
  ],
  includedCourses: [
    { icon: "🌐", name: "AI Mājaslapa", desc: "Būvēšana ar Claude Code, premium dizains, publicēšana" },
    { icon: "🤖", name: "AI funkcijas", desc: "Čatbots, asistents, automatizācijas un e-pasti" },
    { icon: "💼", name: "Bizness & klienti", desc: "Portfolio, cenas, outreach un projektu nodošana" },
  ],
  ctaPrimary: "Sākt Digitālā Speciālista ceļu →",
};

const digitalaisEn: StackPlanModel = {
  ...digitalaisLv,
  name: "Digital Builder",
  tagline: "Build a real AI website with Claude Code and sell it to businesses",
  earn: "€500–€1 800/mo",
  courses: ["AI website", "Claude Code", "AI business features"],
  learn: [
    "Understand why AI completely changed website development",
    "Build a real website with Claude Code — no coding experience needed",
    "Make the design premium and publish the site online",
    "Add an AI chatbot and an on-site AI assistant",
    "Integrate contact forms, emails, and business automations",
    "Build a professional portfolio with real work",
    "Find your first clients and price your service right",
    "Turn this skill into a real business — €500–€1 800/month",
  ],
  skills: [
    "Building websites with Claude Code from scratch",
    "Premium design, animations, and AI visuals",
    "AI chatbot, assistant, and business automations",
    "Domain, publishing, and professional handoff",
    "Finding clients, pricing, and selling the service",
  ],
  heroPill: "⭐ Most popular plan",
  heroBefore: "Build ",
  heroHighlight: "AI websites",
  heroAfter: " with Claude Code and sell them",
  lead: "From understanding the AI revolution to a real website you publish online, enrich with AI features, and sell to businesses. Practical from the very first lesson.",
  topBarPlanLine: "Digital Builder · €59/mo",
  earningRows: [
    { label: "2–3 clients", amount: "€1 000–€3 600/mo" },
    { label: "4–6 clients", amount: "€2 000–€7 200/mo" },
  ],
  includedCourses: [
    { icon: "🌐", name: "AI website", desc: "Built with Claude Code, premium design, publishing" },
    { icon: "🤖", name: "AI features", desc: "Chatbot, assistant, automations, and emails" },
    { icon: "💼", name: "Business & clients", desc: "Portfolio, pricing, outreach, and handoff" },
  ],
  ctaPrimary: "Start the Digital Builder path →",
  modules: [
    {
      id: 1,
      title: "The AI revolution in website development",
      duration: "35 min",
      free: true,
      lessons: [
        {
          id: "1.1",
          title: "How AI completely changed website development",
          type: "video",
          duration: "10 min",
          free: true,
          description:
            "In just a few years website development changed completely. What used to take weeks of work and an expensive dev team can now be done in hours. This lesson shows why right now is the best time to learn to build websites with AI.",
        },
        {
          id: "1.2",
          title: "Why businesses no longer need months or a dev team",
          type: "video",
          duration: "9 min",
          free: true,
          description:
            "Why companies no longer pay thousands for months-long builds — and how that opens the door for you to deliver faster and cheaper.",
        },
        { id: "1.3", title: "Claude Code — why it changes everything", type: "video", duration: "8 min", free: false },
        { id: "1.4", title: "What you'll build in this course (and how to sell it)", type: "video", duration: "8 min", free: false },
      ],
    },
    {
      id: 2,
      title: "Building an AI website with Claude Code",
      duration: "2h 40 min",
      free: false,
      lessons: [
        { id: "2.1", title: "Installing and setting up Claude Code", type: "video", duration: "18 min", free: false },
        { id: "2.2", title: "Creating your first project from scratch", type: "video", duration: "22 min", free: false },
        { id: "2.3", title: "The Claude Code workflow — working efficiently", type: "video", duration: "24 min", free: false },
        { id: "2.4", title: "Writing effective prompts for Claude Code", type: "video", duration: "25 min", free: false },
        { id: "2.5", title: "Building the homepage step by step", type: "video", duration: "26 min", free: false },
        { id: "2.6", title: "Sections and layouts", type: "video", duration: "23 min", free: false },
        { id: "2.7", title: "Responsive design for every device", type: "video", duration: "22 min", free: false },
      ],
    },
    {
      id: 3,
      title: "Improving the design & publishing",
      duration: "2h",
      free: false,
      lessons: [
        { id: "3.1", title: "Making the design look premium", type: "video", duration: "22 min", free: false },
        { id: "3.2", title: "Modern UI & UX improvements", type: "video", duration: "22 min", free: false },
        { id: "3.3", title: "Images and AI-generated visuals", type: "video", duration: "20 min", free: false },
        { id: "3.4", title: "Animations and micro-interactions", type: "video", duration: "18 min", free: false },
        { id: "3.5", title: "Connecting a custom domain", type: "video", duration: "16 min", free: false },
        { id: "3.6", title: "Publishing the website online", type: "video", duration: "22 min", free: false },
      ],
    },
    {
      id: 4,
      title: "AI features for businesses",
      duration: "2h",
      free: false,
      lessons: [
        { id: "4.1", title: "AI chatbot integration", type: "video", duration: "22 min", free: false },
        { id: "4.2", title: "On-site AI website assistant", type: "video", duration: "20 min", free: false },
        { id: "4.3", title: "Contact forms and inquiries", type: "video", duration: "18 min", free: false },
        { id: "4.4", title: "Business automations", type: "video", duration: "22 min", free: false },
        { id: "4.5", title: "Email integrations", type: "video", duration: "18 min", free: false },
        { id: "4.6", title: "Real business examples", type: "video", duration: "20 min", free: false },
      ],
    },
    {
      id: 5,
      title: "Portfolio, clients & selling your service",
      duration: "2h",
      free: false,
      lessons: [
        { id: "5.1", title: "Building a professional portfolio", type: "video", duration: "22 min", free: false },
        { id: "5.2", title: "Pricing your service", type: "video", duration: "20 min", free: false },
        { id: "5.3", title: "Finding your first clients", type: "video", duration: "20 min", free: false },
        { id: "5.4", title: "Outreach templates and messages", type: "text", duration: "18 min", free: false },
        { id: "5.5", title: "Delivering projects professionally", type: "video", duration: "20 min", free: false },
        { id: "5.6", title: "Growing this into a real business", type: "video", duration: "20 min", free: false },
      ],
    },
  ],
};

export const digitalaisStack: StackPlanByLocale = { lv: digitalaisLv, en: digitalaisEn };
