import type { AppLocale } from "@/i18n/routing";
import type { DetailMarketingCourse } from "@/content/marketing/marketingDetailCourse.types";

const saturaLv: DetailMarketingCourse = {
  title: "Satura Speciālists",
  subtitle: "Kļūsti par AI sociālo tīklu pārvaldnieku — pārvaldi uzņēmumu sociālos tīklus ar AI",
  description:
    "Viss, kas vajadzīgs, lai pilnībā pārvaldītu uzņēmuma sociālos tīklus ar AI. Mācies AI → veido profesionālu saturu → izveido portfolio → iegūsti maksājošus klientus. Bez kameras, bez programmēšanas — reāls ceļš uz 300€–1500€ mēnesī.",
  earn: "300€–1500€/mēn",
  difficulty: "Iesācējs",
  tag: "Jauns",
  totalDuration: "9h",
  totalLessons: 26,
  totalModules: 3,
  students: 134,
  rating: 4.9,
  instructor: {
    name: "Līga Ozola",
    role: "AI Sociālo Tīklu Stratēģe",
    avatar: "LO",
    bio: "6+ gadi sociālo mediju satura veidošanā Latvijas zīmoliem. Pēdējos 2 gadus pilnībā pārgājusi uz AI darbplūsmām — AI attēli, faceless video un automatizēta publicēšana. Personīgi pārvalda 9 klientu sociālos kontus.",
    students: 380,
    courses: 3,
  },
  tools: [
    { name: "ChatGPT", desc: "Captions, hashtagi un piedāvājumi", color: "#00ff88" },
    { name: "Canva AI", desc: "Banneri, karuseļi un feed dizains", color: "#f59e0b" },
    { name: "Midjourney", desc: "AI attēlu ģenerēšana", color: "#8b5cf6" },
    { name: "Runway ML", desc: "AI video ģenerēšana", color: "#a855f7" },
    { name: "CapCut", desc: "Video montāža un subtitri", color: "#00d4ff" },
    { name: "Pika", desc: "AI video no teksta", color: "#ec4899" },
    { name: "Buffer", desc: "Publicēšanas grafiks", color: "#ef4444" },
  ],
  learn: [
    "Pārvaldīt uzņēmuma sociālos tīklus no A līdz Z ar AI",
    "Ģenerēt AI attēlus, bannerus un karuseļus profesionālā kvalitātē",
    "Veidot AI video, Reels un reklāmas bez kameras",
    "Izveidot mēneša satura plānu vienā piegājienā",
    "Uzbūvēt pārliecinošu portfolio no nulles",
    "Uzrunāt uzņēmumus ar gatavām DM un e-pasta veidnēm",
    "Sagatavot cenu piedāvājumu un iegūt pirmos maksājošos klientus",
  ],
  modules: [
    {
      id: 1,
      title: "AI Sociālo Tīklu Pārvaldība",
      duration: "3h 30 min",
      cover: "/ai/card-social.jpg",
      summary: "Viss, lai kļūtu par AI sociālo tīklu pārvaldnieku — attēli, banneri, karuseļi un satura plāns.",
      lessons: [
        { id: "1-1", title: "Kā darbojas sociālo tīklu tirgus Latvijā", type: "video", duration: "18 min", free: true, description: "Kāpēc uzņēmumi maksā par sociālo tīklu pārvaldību, kādas platformas dominē Latvijā un kā AI maina šo nozari — ar reāliem cenu piemēriem." },
        { id: "1-2", title: "Kādus pakalpojumus vari piedāvāt uzņēmumiem", type: "video", duration: "16 min", free: true, description: "Konkrēts pakalpojumu saraksts, ko vari sākt pārdot jau šonedēļ — attēli, video, feed pārvaldība un mēneša satura plāns." },
        { id: "1-3", title: "AI attēlu ģenerēšana", type: "video", duration: "24 min", description: "Midjourney un ChatGPT attēli — prompt formulas komerciālas kvalitātes vizuāļiem, kas izskatās kā no aģentūras." },
        { id: "1-4", title: "AI reklāmu baneri", type: "video", duration: "22 min", description: "Kā ģenerēt reklāmu bannerus dažādiem formātiem — Stories, feed un reklāmas — ar AI un Canva brand kit." },
        { id: "1-5", title: "Instagram karuseļu dizains", type: "video", duration: "24 min", description: "Soli pa solim karuseļa veidošana, kas notur uzmanību līdz pēdējam slaidam — struktūra, dizains un teksts." },
        { id: "1-6", title: "Facebook un Instagram postu dizains", type: "video", duration: "22 min", description: "Vienots feed dizains, kur 9 posti izskatās kā viens saskaņots zīmols — šabloni un AI palīgi." },
        { id: "1-7", title: "Caption rakstīšana ar ChatGPT", type: "video", duration: "18 min", description: "Prompt sistēma captions ģenerēšanai latviešu valodā — hook, vērtība un aicinājums uz darbību." },
        { id: "1-8", title: "Hashtag un SEO ģenerēšana", type: "text", duration: "16 min", description: "Kā ar AI atrast pareizos hashtagus un atslēgvārdus, lai saturs sasniedz vairāk cilvēku bez reklāmas budžeta." },
        { id: "1-9", title: "Mēneša satura plāna izveide", type: "task", duration: "26 min", description: "30 dienu satura plāns vienā piegājienā — tēmas, formāti un publicēšanas ritms, ko klients uzreiz saprot." },
        { id: "1-10", title: "Canva + AI profesionālai satura izveidei", type: "video", duration: "24 min", description: "Magic Design, brand kit un AI fona noņemšana — kā ražot nedēļas saturu dažās stundās." },
      ],
    },
    {
      id: 2,
      title: "AI Video Satura Izveide",
      duration: "3h",
      cover: "/ai/card-ad.jpg",
      summary: "Veido AI video, Reels un reklāmas — no skripta līdz gatavam materiālam klientam.",
      lessons: [
        { id: "2-1", title: "AI Faceless Video", type: "video", duration: "24 min", description: "Kā veidot video bez kameras un sejas — koncepts, skripts un AI rīku komplekts no nulles." },
        { id: "2-2", title: "AI video ģenerēšana", type: "video", duration: "26 min", description: "Praktiska video ģenerēšana ar Runway, Pika un Kling — stila izvēle, kustība, ilgums un eksportēšana." },
        { id: "2-3", title: "AI produktu reklāmas", type: "video", duration: "22 min", description: "Kā ar AI izveidot produktu reklāmas video, kas izskatās dārgi — pat bez paša produkta rokās." },
        { id: "2-4", title: "Video montāža", type: "video", duration: "24 min", description: "Montāža CapCut — griezumi, pārejas, subtitri un mūzika, lai video ir gatavs 15 minūtēs." },
        { id: "2-5", title: "Reels un TikTok izveide", type: "video", duration: "22 min", description: "Vertikālā formāta video, kas tiek skatīts līdz beigām — hook pirmajās 3 sekundēs un ritms." },
        { id: "2-6", title: "B-roll un AI vizuāli", type: "video", duration: "20 min", description: "Kā ar AI ģenerēt B-roll un vizuāļus, kas papildina stāstu un padara video profesionālu." },
        { id: "2-7", title: "Reklāmas video uzņēmumiem", type: "video", duration: "22 min", description: "Reklāmas video struktūra, kas pārdod — no brīfa līdz gatavam materiālam uzņēmuma kampaņai." },
        { id: "2-8", title: "Gatava video nodošana klientam", type: "text", duration: "20 min", description: "Nodošanas template — kā prezentēt video, savākt komentārus un saņemt apstiprinājumu bez bezgalīgām labošanām." },
      ],
    },
    {
      id: 3,
      title: "Portfolio, Klienti un Pirmie Ienākumi",
      duration: "2h 30 min",
      cover: "/ai/card-portfolio.jpg",
      summary: "Portfolio, cenas un pirmie maksājošie klienti — pārvērt prasmes ienākumos.",
      lessons: [
        { id: "3-1", title: "Portfolio izveide", type: "video", duration: "20 min", description: "Kā uzbūvēt pārliecinošu portfolio, pat ja vēl nav neviena reāla klienta — demo darbi un kārtojums." },
        { id: "3-2", title: "AI mājaslapas portfolio", type: "video", duration: "22 min", description: "Vienkārša portfolio mājaslapa ar AI — bez programmēšanas, gatava dažās stundās un izskatās profesionāli." },
        { id: "3-3", title: "Pakalpojumu cenu izveide", type: "video", duration: "18 min", description: "Kā veidot pakalpojumu paketes un noteikt cenas, lai pelnītu, nevis strādātu par velti." },
        { id: "3-4", title: "Piedāvājuma ģenerēšana ar ChatGPT", type: "text", duration: "18 min", description: "Prompt veidne komerciāla piedāvājuma sagatavošanai, kas izskatās profesionāli un attaisno cenu." },
        { id: "3-5", title: "Kā uzrunāt uzņēmumus", type: "video", duration: "20 min", description: "Kur atrast klientus un kā uzrunāt uzņēmumus tā, lai saņemtu atbildi — ne spams, bet vērtība." },
        { id: "3-6", title: "Gatavas DM un e-pastu veidnes", type: "text", duration: "16 min", description: "Copy-paste ziņu veidnes ar reāliem rezultātiem — DM un e-pasts, kas rezervēja tikšanās." },
        { id: "3-7", title: "Klienta onboarding", type: "video", duration: "18 min", description: "Kā uzsākt sadarbību ar jaunu klientu gludi — jautājumi, piekļuves un pirmā mēneša plāns." },
        { id: "3-8", title: "Kā iegūt pirmos maksājošos klientus", type: "video", duration: "18 min", description: "No sarunas līdz parakstam un rēķinam — kā noslēgt darījumu un saņemt pirmo samaksu." },
      ],
    },
  ],
};

const saturaEn: DetailMarketingCourse = {
  title: "Content Specialist",
  subtitle: "Become an AI social media manager — run companies' social media with AI",
  description:
    "Everything you need to fully run a company's social media with AI. Learn AI → create professional content → build your portfolio → get paying clients. No camera, no engineering — a real path to €300–€1,500/month.",
  earn: "€300–€1,500/mo",
  difficulty: "Beginner",
  tag: "New",
  totalDuration: "9h",
  totalLessons: 26,
  totalModules: 3,
  students: 134,
  rating: 4.9,
  instructor: {
    name: "Līga Ozola",
    role: "AI Social Media Strategist",
    avatar: "LO",
    bio: "Six years building social content for Latvian brands, the last two fully on AI workflows—AI images, faceless video, and automated publishing. Personally manages social accounts for nine clients.",
    students: 380,
    courses: 3,
  },
  tools: [
    { name: "ChatGPT", desc: "Captions, hashtags, and proposals", color: "#00ff88" },
    { name: "Canva AI", desc: "Banners, carousels, and feed design", color: "#f59e0b" },
    { name: "Midjourney", desc: "AI image generation", color: "#8b5cf6" },
    { name: "Runway ML", desc: "Generative AI video", color: "#a855f7" },
    { name: "CapCut", desc: "Editing and captions", color: "#00d4ff" },
    { name: "Pika", desc: "Text-to-video", color: "#ec4899" },
    { name: "Buffer", desc: "Publishing calendar", color: "#ef4444" },
  ],
  learn: [
    "Run a company's social media end to end with AI",
    "Generate AI images, banners, and carousels at agency quality",
    "Create AI video, Reels, and ads without a camera",
    "Build a full month of content in a single pass",
    "Assemble a convincing portfolio from scratch",
    "Reach businesses with proven DM and email templates",
    "Package pricing and land your first paying clients",
  ],
  modules: [
    {
      id: 1,
      title: "AI Social Media Management",
      duration: "3h 30 min",
      cover: "/ai/card-social.jpg",
      summary: "Everything to become an AI social media manager — images, banners, carousels, and a content plan.",
      lessons: [
        { id: "1-1", title: "How the social media market works in Latvia", type: "video", duration: "18 min", free: true, description: "Why businesses pay for social media management, which platforms matter locally, and how AI changes the game—with real pricing examples." },
        { id: "1-2", title: "Services you can offer businesses", type: "video", duration: "16 min", free: true, description: "A concrete service menu you can start selling this week—images, video, feed management, and monthly content plans." },
        { id: "1-3", title: "AI image generation", type: "video", duration: "24 min", description: "Midjourney and ChatGPT images—prompt formulas for commercial-grade visuals that look like agency work." },
        { id: "1-4", title: "AI ad banners", type: "video", duration: "22 min", description: "How to generate ad banners for every format—Stories, feed, and paid ads—with AI and a Canva brand kit." },
        { id: "1-5", title: "Instagram carousel design", type: "video", duration: "24 min", description: "Step-by-step carousels that hold attention to the last slide—structure, design, and copy." },
        { id: "1-6", title: "Facebook and Instagram post design", type: "video", duration: "22 min", description: "A cohesive feed where nine posts read as one brand—templates and AI helpers." },
        { id: "1-7", title: "Caption writing with ChatGPT", type: "video", duration: "18 min", description: "A prompt system for captions—hook, value, and a clear call to action." },
        { id: "1-8", title: "Hashtag and SEO generation", type: "text", duration: "16 min", description: "How to use AI to find the right hashtags and keywords so content reaches more people without ad spend." },
        { id: "1-9", title: "Building a monthly content plan", type: "task", duration: "26 min", description: "A 30-day content plan in one pass—topics, formats, and a publishing rhythm a client understands instantly." },
        { id: "1-10", title: "Canva + AI for professional content", type: "video", duration: "24 min", description: "Magic Design, brand kit, and AI background removal—produce a week of content in a couple of hours." },
      ],
    },
    {
      id: 2,
      title: "AI Video Content Creation",
      duration: "3h",
      cover: "/ai/card-ad.jpg",
      summary: "Create AI video, Reels, and ads—from script to a finished asset for the client.",
      lessons: [
        { id: "2-1", title: "AI Faceless Video", type: "video", duration: "24 min", description: "How to make video without a camera or face—concept, script, and the AI tool stack from scratch." },
        { id: "2-2", title: "AI video generation", type: "video", duration: "26 min", description: "Hands-on generation with Runway, Pika, and Kling—style, motion, duration, and exports." },
        { id: "2-3", title: "AI product ads", type: "video", duration: "22 min", description: "How to build product ad videos that look expensive—even without the product in hand." },
        { id: "2-4", title: "Video editing", type: "video", duration: "24 min", description: "Editing in CapCut—cuts, transitions, captions, and music so the video is ready in 15 minutes." },
        { id: "2-5", title: "Reels and TikTok creation", type: "video", duration: "22 min", description: "Vertical video watched to the end—a hook in the first 3 seconds and the right pacing." },
        { id: "2-6", title: "B-roll and AI visuals", type: "video", duration: "20 min", description: "How to generate B-roll and visuals with AI that support the story and make the video look professional." },
        { id: "2-7", title: "Ad video for businesses", type: "video", duration: "22 min", description: "An ad video structure that sells—from brief to a finished asset for a company's campaign." },
        { id: "2-8", title: "Delivering the finished video", type: "text", duration: "20 min", description: "A handoff template—how to present the video, collect feedback, and get sign-off without endless revisions." },
      ],
    },
    {
      id: 3,
      title: "Portfolio, Clients, and First Revenue",
      duration: "2h 30 min",
      cover: "/ai/card-portfolio.jpg",
      summary: "Portfolio, pricing, and first paying clients—turn your skills into income.",
      lessons: [
        { id: "3-1", title: "Building a portfolio", type: "video", duration: "20 min", description: "How to build a convincing portfolio even before your first real client—demo work and layout." },
        { id: "3-2", title: "AI website portfolio", type: "video", duration: "22 min", description: "A simple portfolio site with AI—no coding, ready in a few hours, and it looks professional." },
        { id: "3-3", title: "Pricing your services", type: "video", duration: "18 min", description: "How to package services and set prices so you earn instead of working for free." },
        { id: "3-4", title: "Proposal generation with ChatGPT", type: "text", duration: "18 min", description: "A prompt template for a commercial proposal that looks professional and justifies the price." },
        { id: "3-5", title: "How to reach businesses", type: "video", duration: "20 min", description: "Where to find clients and how to reach out so you get a reply—value, not spam." },
        { id: "3-6", title: "Ready DM and email templates", type: "text", duration: "16 min", description: "Copy-paste outreach templates with real results—DM and email that booked meetings." },
        { id: "3-7", title: "Client onboarding", type: "video", duration: "18 min", description: "How to start with a new client smoothly—questions, access, and a first-month plan." },
        { id: "3-8", title: "Landing your first paying clients", type: "video", duration: "18 min", description: "From conversation to signature and invoice—how to close the deal and get your first payment." },
      ],
    },
  ],
};

export const saturaMarketingCourseByLocale: Record<AppLocale, DetailMarketingCourse> = {
  lv: saturaLv,
  en: saturaEn,
};
