import type { StackPlanByLocale, StackPlanModel } from "./stackTypes";

const saturaLv: StackPlanModel = {
  name: "Satura Speciālists",
  price: "29",
  tagline: "Iemācies veidot AI saturu un pārdot to uzņēmumiem",
  earn: "300€–1 500€/mēn",
  color: "#a855f7",
  glow: "168,85,247",
  courses: ["AI Faceless Video", "Sociālo Tīklu Pārvaldība"],
  stats: { lessons: 28, modules: 4, hours: "6h 40 min", students: 134 },
  learn: [
    "Izveidot AI video bez kameras — no skripta līdz publicēšanai",
    "Pārvaldīt sociālos tīklus ar AI rīkiem",
    "Veidot reklāmas bannerus un feed dizainu",
    "Uzrunāt pirmos klientus ar gatavām ziņu veidnēm",
    "Sagatavot profesionālu cenu piedāvājumu",
    "Izveidot portfolio no 0 — pat bez pieredzes",
    "Nopelnīt 300€–1500€ mēnesī kā Satura Speciālists",
  ],
  skills: [
    "Kā izveidot portfolio no 0",
    "Kā uzrunāt pirmos klientus",
    "Kā sagatavot cenu piedāvājumu",
    "Copy-paste ziņu veidnes",
  ],
  modules: [
    {
      id: 1,
      title: "Ievads — Kā nopelnīt ar AI saturu",
      duration: "38 min",
      free: true,
      lessons: [
        {
          id: "1.1",
          title: "Kā darbojas sociālo mediju tirgus Latvijā",
          type: "video",
          duration: "8 min",
          free: true,
          description:
            "Uzzini, kāpēc uzņēmumi maksā par sociālo mediju saturu, kādas platformas dominē Latvijā un kā AI maina šo nozari. Pārskatīs reālus piemērus ar cenām.",
        },
        { id: "1.2", title: "Kādus pakalpojumus vari piedāvāt uzreiz", type: "video", duration: "10 min", free: false },
        { id: "1.3", title: "Rīku komplekts iesācējam (bezmaksas + maksas)", type: "text", duration: "6 min", free: false },
        { id: "1.4", title: "Pirmais klients — reāls piemērs", type: "video", duration: "14 min", free: false },
      ],
    },
    {
      id: 2,
      title: "AI Faceless Video — no nulles līdz publicēšanai",
      duration: "2h 10 min",
      free: false,
      lessons: [
        { id: "2.1", title: "Kontu iestatīšana: CapCut, Canva, ChatGPT", type: "video", duration: "18 min", free: false },
        { id: "2.2", title: "Skripta veidošana ar AI — pilns process", type: "video", duration: "22 min", free: false },
        { id: "2.3", title: "Video ģenerēšana: Runway, Pika, Kling", type: "video", duration: "30 min", free: false },
        { id: "2.4", title: "Subtitri, mūzika un montāža", type: "video", duration: "25 min", free: false },
        { id: "2.5", title: "Publicēšana un laiku plānošana", type: "video", duration: "15 min", free: false },
        { id: "2.6", title: "Klientam — ziņojums un nodošana", type: "text", duration: "20 min", free: false },
      ],
    },
    {
      id: 3,
      title: "Sociālo Tīklu Pārvaldība ar AI",
      duration: "2h 30 min",
      free: false,
      lessons: [
        { id: "3.1", title: "Klienta auditorijas analīze ar AI", type: "video", duration: "20 min", free: false },
        { id: "3.2", title: "Content plāna veidošana (30 dienas)", type: "video", duration: "25 min", free: false },
        { id: "3.3", title: "AI banneru radīšana Canvā", type: "video", duration: "22 min", free: false },
        { id: "3.4", title: "Instagram un TikTok feed dizains", type: "video", duration: "28 min", free: false },
        { id: "3.5", title: "Copy ar AI — caption, hashtagi, CTA", type: "video", duration: "20 min", free: false },
        { id: "3.6", title: "Ikmēneša atskaite klientam", type: "text", duration: "15 min", free: false },
      ],
    },
    {
      id: 4,
      title: "Portfolio, Klienti un Pirmā Nauda",
      duration: "1h 22 min",
      free: false,
      lessons: [
        { id: "4.1", title: "Portfolio no 0 — bez pieredzes", type: "video", duration: "20 min", free: false },
        { id: "4.2", title: "Klientu uzrunāšana: DM un e-pasta veidnes", type: "text", duration: "15 min", free: false },
        { id: "4.3", title: "Cenu piedāvājums — ko iekļaut", type: "video", duration: "18 min", free: false },
        { id: "4.4", title: "Pirmā tikšanās ar klientu — kā runāt", type: "video", duration: "15 min", free: false },
        { id: "4.5", title: "Līgums, rēķins un samaksa", type: "text", duration: "14 min", free: false },
      ],
    },
  ],
  heroPill: "🎬 Satura Speciālists",
  heroBefore: "Iemācies veidot ",
  heroHighlight: "AI saturu",
  heroAfter: " un pārdot to uzņēmumiem",
  lead: "Praktiska platforma — no rīku iestatīšanas līdz pirmajam klientam. Bez programmēšanas. Bez kameras.",
  topBarPlanLine: "Satura Speciālists · €29/mēn",
  earningRows: [
    { label: "2–3 klienti", amount: "€600–€1 800/mēn" },
    { label: "4–6 klienti", amount: "€1 200–€3 600/mēn" },
  ],
  includedCourses: [
    { icon: "🎬", name: "AI Faceless Video", desc: "Satura veidošana bez kameras" },
    { icon: "📱", name: "Sociālo Tīklu Pārvaldība", desc: "AI video, banneri, feed dizains" },
  ],
  ctaPrimary: "Sākt Satura Speciālista ceļu →",
};

const saturaEn: StackPlanModel = {
  ...saturaLv,
  name: "Content Specialist",
  earn: "€300–€1 500/mo",
  courses: ["AI Faceless Video", "Social Media OS"],
  tagline: "Learn to ship AI-powered content—and sell it to businesses",
  learn: [
    "Produce AI-assisted video without going on camera—from script to publish",
    "Operate social feeds with AI tools",
    "Design ad creatives and carousel-ready layouts",
    "Reach first clients with proven DM + email skeletons",
    "Package pricing proposals that feel premium",
    "Build a credible portfolio starting from zero",
    "Earn €300–€1 500/month as a Content Specialist",
  ],
  skills: [
    "How to assemble a portfolio with zero prior clients",
    "How to outreach without sounding templated",
    "What to include in a commercial proposal",
    "Copy-ready DM + email snippets",
  ],
  heroPill: "🎬 Content Specialist track",
  heroBefore: "Learn to build ",
  heroHighlight: "AI-powered content",
  heroAfter: " and sell it to businesses",
  lead: "Hands-on platform—from tooling setup through your first paid client. No engineering. No camera fear.",
  topBarPlanLine: "Content Specialist · €29/mo",
  earningRows: [
    { label: "2–3 retainers", amount: "€600–€1 800/mo" },
    { label: "4–6 retainers", amount: "€1 200–€3 600/mo" },
  ],
  includedCourses: [
    { icon: "🎬", name: "AI Faceless Video", desc: "Camera-free storytelling with generative tools" },
    { icon: "📱", name: "Social Media OS", desc: "AI clips, ad blocks, and feed systems" },
  ],
  ctaPrimary: "Start the Content Specialist path →",
  modules: [
    {
      id: 1,
      title: "Intro — Making money with AI content",
      duration: "38 min",
      free: true,
      lessons: [
        {
          id: "1.1",
          title: "How the social content market works in Latvia",
          type: "video",
          duration: "8 min",
          free: true,
          description:
            "Why SMBs pay for social operations, which platforms matter locally, and how AI compresses production time—with pricing snapshots.",
        },
        { id: "1.2", title: "Services you can sell immediately", type: "video", duration: "10 min", free: false },
        { id: "1.3", title: "Tool stack for beginners (free + paid)", type: "text", duration: "6 min", free: false },
        { id: "1.4", title: "First client walkthrough (real example)", type: "video", duration: "14 min", free: false },
      ],
    },
    {
      id: 2,
      title: "AI Faceless Video — zero to published",
      duration: "2h 10 min",
      free: false,
      lessons: [
        { id: "2.1", title: "Account setup: CapCut, Canva, ChatGPT", type: "video", duration: "18 min", free: false },
        { id: "2.2", title: "Scripting with AI — full workflow", type: "video", duration: "22 min", free: false },
        { id: "2.3", title: "Video generation labs: Runway, Pika, Kling", type: "video", duration: "30 min", free: false },
        { id: "2.4", title: "Music, captions, and editing polish", type: "video", duration: "25 min", free: false },
        { id: "2.5", title: "Publishing calendars that clients understand", type: "video", duration: "15 min", free: false },
        { id: "2.6", title: "Client handoff memo + asset package", type: "text", duration: "20 min", free: false },
      ],
    },
    {
      id: 3,
      title: "Social Media OS with AI",
      duration: "2h 30 min",
      free: false,
      lessons: [
        { id: "3.1", title: "Audience research prompts that save hours", type: "video", duration: "20 min", free: false },
        { id: "3.2", title: "30-day content blueprint", type: "video", duration: "25 min", free: false },
        { id: "3.3", title: "Canva automation for promo suites", type: "video", duration: "22 min", free: false },
        { id: "3.4", title: "Instagram & TikTok feed systems", type: "video", duration: "28 min", free: false },
        { id: "3.5", title: "AI copy for captions, hooks, CTAs", type: "video", duration: "20 min", free: false },
        { id: "3.6", title: "Monthly client reporting template", type: "text", duration: "15 min", free: false },
      ],
    },
    {
      id: 4,
      title: "Portfolio, Outreach, First Revenue",
      duration: "1h 22 min",
      free: false,
      lessons: [
        { id: "4.1", title: "Portfolio from scratch (no fluff)", type: "video", duration: "20 min", free: false },
        { id: "4.2", title: "DM + email scripts that booked meetings", type: "text", duration: "15 min", free: false },
        { id: "4.3", title: "Commercial proposals — what buyers expect", type: "video", duration: "18 min", free: false },
        { id: "4.4", title: "Discovery call flow for nervous founders", type: "video", duration: "15 min", free: false },
        { id: "4.5", title: "Contracts, invoices, and getting paid", type: "text", duration: "14 min", free: false },
      ],
    },
  ],
};

export const saturaStack: StackPlanByLocale = { lv: saturaLv, en: saturaEn };
