import { createRequire } from 'module';
import { readdirSync } from 'fs';
const require = createRequire(import.meta.url);
const puppeteer = require('puppeteer');
const dir = 'd:/Documents/Desktop/AI_APP/temporary screenshots';
let n = readdirSync(dir).filter(f => f.endsWith('.png')).length;
const b = await puppeteer.launch({ headless: 'new', args: ['--no-sandbox','--disable-setuid-sandbox'] });
const p = await b.newPage();
await p.setViewport({ width: 1440, height: 900, deviceScaleFactor: 2 });
await p.goto('http://localhost:3000/lv', { waitUntil: 'networkidle0', timeout: 60000 });
const y = await p.evaluate(() => { const e = document.getElementById('courses'); return e.getBoundingClientRect().top + window.scrollY; });
await p.evaluate(yy => window.scrollTo({ top: yy+220, behavior: 'instant' }), y);
await new Promise(r => setTimeout(r, 1600));
n++; const f = dir + '/screenshot-' + n + '-premium-card.png';
await p.screenshot({ path: f }); console.log(f);
await b.close();
